# Generated by Django 4.2.6 on 2023-10-29 08:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID unico para la tabla', primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Introduce la descripcion', max_length=200)),
            ],
            options={
                'ordering': ['description'],
            },
        ),
    ]
