# Generated by Django 5.1.6 on 2025-04-21 20:11

from django.db import migrations

SQL_FORWARD = """
UPDATE invoice_processor_invoicetype
SET account_id=196
WHERE id=1;
UPDATE invoice_processor_invoicetype
SET account_id=174
WHERE id=2;
"""

# (Opcional) Define el SQL para revertir la migración (eliminar los datos)
SQL_REVERSE = """
UPDATE invoice_processor_invoicetype
SET account_id=null
WHERE id=1;
UPDATE invoice_processor_invoicetype
SET account_id=null
WHERE id=2;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('invoice_processor', '0004_invoicetype_account'),
    ]

    operations = [
        # Ejecuta el SQL para insertar los datos
        migrations.RunSQL(SQL_FORWARD, reverse_sql=SQL_REVERSE),
    ]


