
Insert into categories (description) values ('Alquiler:Casa');
Insert into categories (description) values ('Alquiler:Comision');
Insert into categories (description) values ('Alquiler:Fianzas');
Insert into categories (description) values ('Alquiler:Garaje');
Insert into categories (description) values ('Amigos');
Insert into categories (description) values ('Belleza');
Insert into categories (description) values ('Belleza:Estetica');
Insert into categories (description) values ('Belleza:Maquillaje');
Insert into categories (description) values ('Belleza:Ropa');
Insert into categories (description) values ('Casa:Decoracion y Otros');
Insert into categories (description) values ('Casa:Reparaciones');
Insert into categories (description) values ('Cobros');
Insert into categories (description) values ('Cobros:Cobro Deudas');
Insert into categories (description) values ('Cobros:Descuentos');
Insert into categories (description) values ('Cobros:Devoluciones');
Insert into categories (description) values ('Cobros:Intereses');
Insert into categories (description) values ('Cobros:IRPF');
Insert into categories (description) values ('Coche');
Insert into categories (description) values ('Coche:Gasolina');
Insert into categories (description) values ('Coche:Iman para el movil');
Insert into categories (description) values ('Coche:ITV');
Insert into categories (description) values ('Coche:Lavado');
Insert into categories (description) values ('Coche:Parking');
Insert into categories (description) values ('Coche:Pitorros');
Insert into categories (description) values ('Coche:Reparaciones');
Insert into categories (description) values ('Coche:Rodaje');
Insert into categories (description) values ('Comida:Bares y Restaurantes');
Insert into categories (description) values ('Comida:Supermercado y Otros');
Insert into categories (description) values ('Contabilidad Empresa');
Insert into categories (description) values ('Contabilidad Empresa:47270000 - H.P. IGIC SOPORTADO');
Insert into categories (description) values ('Contabilidad Empresa:47770000 - H.P. IGIC REPERCUTIDO');
Insert into categories (description) values ('Contabilidad Empresa:60000000 - COMPRAS DE MERCADERIA');
Insert into categories (description) values ('Contabilidad Empresa:62200000 - REPARACION Y CONSERVACION');
Insert into categories (description) values ('Contabilidad Empresa:62500000 - PRIMAS DE SEGURO');
Insert into categories (description) values ('Contabilidad Empresa:62710000 - RELACCIONES PUBLICAS');
Insert into categories (description) values ('Contabilidad Empresa:62800001 - SUMINISTRO DE COMBUSTIBLE');
Insert into categories (description) values ('Contabilidad Empresa:62900000 - OTROS SERVICIOS');
Insert into categories (description) values ('Contabilidad Empresa:62900001 - OTROS SERV TELECOMUNICACIONES');
Insert into categories (description) values ('Contabilidad Empresa:63100000 - TRIBUTOS');
Insert into categories (description) values ('Contabilidad Empresa:64200001 - SEG SOC AUTONOMO');
Insert into categories (description) values ('Contabilidad Empresa:70000000 - VENTAS DE MERCADERIA');
Insert into categories (description) values ('Contabilidad Empresa:76900000 - OTROS INGRESOS FINANCIEROS');
Insert into categories (description) values ('Estudios');
Insert into categories (description) values ('Estudios:Autoescuela');
Insert into categories (description) values ('Estudios:Clases Particulares');
Insert into categories (description) values ('Estudios:Cuota Colegio');
Insert into categories (description) values ('Estudios:Fotocopias');
Insert into categories (description) values ('Estudios:Libros y Revistas');
Insert into categories (description) values ('Estudios:Material Escolar');
Insert into categories (description) values ('Estudios:Matriculas');
Insert into categories (description) values ('Familia');
Insert into categories (description) values ('Fauna y Flora:Pajaros');
Insert into categories (description) values ('Fauna y Flora:Peces');
Insert into categories (description) values ('Fauna y Flora:Plantas');
Insert into categories (description) values ('Fauna y Flora:Tortugas');
Insert into categories (description) values ('Gastos Varios');
Insert into categories (description) values ('Hobbies');
Insert into categories (description) values ('Hobbies:Artes Marciales');
Insert into categories (description) values ('Hobbies:Baile');
Insert into categories (description) values ('Hobbies:Bicicleta');
Insert into categories (description) values ('Hobbies:Buceo');
Insert into categories (description) values ('Hobbies:Ciclismo');
Insert into categories (description) values ('Hobbies:Futbol');
Insert into categories (description) values ('Hobbies:Gimanacio');
Insert into categories (description) values ('Hobbies:Informatica');
Insert into categories (description) values ('Hobbies:Padel y Tenis');
Insert into categories (description) values ('Hobbies:Parques');
Insert into categories (description) values ('Hobbies:Pesca');
Insert into categories (description) values ('Hobbies:Piscina');
Insert into categories (description) values ('Ingresos Varios');
Insert into categories (description) values ('Inversión:Ganancia Inversion FI');
Insert into categories (description) values ('Inversión:Ganancia Inversión ST');
Insert into categories (description) values ('Juguetes');
Insert into categories (description) values ('Loan Payment');
Insert into categories (description) values ('Loan Payment:Interest');
Insert into categories (description) values ('Ocio');
Insert into categories (description) values ('Ocio:Acampadas');
Insert into categories (description) values ('Ocio:Apuestas y Loterias');
Insert into categories (description) values ('Ocio:Atracciones y Parques');
Insert into categories (description) values ('Ocio:Chuletadas');
Insert into categories (description) values ('Ocio:Cine');
Insert into categories (description) values ('Ocio:Cine y Espectaculs');
Insert into categories (description) values ('Ocio:Conciertos y Espectaculos');
Insert into categories (description) values ('Ocio:Discoteca y Fiestas');
Insert into categories (description) values ('Ocio:Ferias');
Insert into categories (description) values ('Ocio:Recreativos');
Insert into categories (description) values ('Ocio:Souvenirs');
Insert into categories (description) values ('Ocio:Viajes y Vacaciones');
Insert into categories (description) values ('Ocio:Videoclub');
Insert into categories (description) values ('Ocio:Videojuegos');
Insert into categories (description) values ('Pago Servicios:Agua');
Insert into categories (description) values ('Pago Servicios:Antivirus');
Insert into categories (description) values ('Pago Servicios:Basura');
Insert into categories (description) values ('Pago Servicios:Cloud');
Insert into categories (description) values ('Pago Servicios:Fianza');
Insert into categories (description) values ('Pago Servicios:Filtrado de Agua');
Insert into categories (description) values ('Pago Servicios:Gas');
Insert into categories (description) values ('Pago Servicios:Luz');
Insert into categories (description) values ('Pago Servicios:Musica');
Insert into categories (description) values ('Pago Servicios:Programa Contabilidad');
Insert into categories (description) values ('Pago Servicios:Servicio de Almacenamiento');
Insert into categories (description) values ('Pago Servicios:Telefonia');
Insert into categories (description) values ('Pago Servicios:TV Pay per View');
Insert into categories (description) values ('Pagos');
Insert into categories (description) values ('Pagos:Aduana');
Insert into categories (description) values ('Pagos:Comisiones');
Insert into categories (description) values ('Pagos:Comunidad');
Insert into categories (description) values ('Pagos:Contribucion IBI');
Insert into categories (description) values ('Pagos:DineroDado');
Insert into categories (description) values ('Pagos:Donaciones');
Insert into categories (description) values ('Pagos:Impuestos');
Insert into categories (description) values ('Pagos:IRPF');
Insert into categories (description) values ('Pagos:Notarios y Abogados');
Insert into categories (description) values ('Pagos:Sanciones');
Insert into categories (description) values ('Prestamos:Ptmos no Bancarios');
Insert into categories (description) values ('Programa Contabilidad:70500000 - PRESTACION DE SERVICIOS');
Insert into categories (description) values ('Regalos');
Insert into categories (description) values ('Salud');
Insert into categories (description) values ('Salud:Farmacia');
Insert into categories (description) values ('Salud:Medico');
Insert into categories (description) values ('Salud:Otros');
Insert into categories (description) values ('Seguros');
Insert into categories (description) values ('Seguros:Coche');
Insert into categories (description) values ('Seguros:Hogar');
Insert into categories (description) values ('Seguros:Salud');
Insert into categories (description) values ('Seguros:Vida');
Insert into categories (description) values ('Sueldo');
Insert into categories (description) values ('Sueldo:Horas Extras');
Insert into categories (description) values ('Sueldo:Pagos Gastos Empresa');
Insert into categories (description) values ('Sueldo:Trabajo externo');
Insert into categories (description) values ('Transporte');
Insert into categories (description) values ('Venta de Articulos');