# Generated by Django 5.1.6 on 2025-02-24 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='padre',
            new_name='parent',
        ),
    ]
