# Generated by Django 5.1.6 on 2025-02-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_entry_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
