# Generated by Django 5.1.6 on 2025-02-25 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_remove_account_attachment_remove_entry_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='level',
        ),
        migrations.RemoveField(
            model_name='account',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='account',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='account',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='registros.account'),
        ),
    ]
