# Generated by Django 5.1.6 on 2025-02-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_remove_account_level_remove_account_lft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
    ]
