# Generated by Django 5.1.6 on 2025-02-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0010_remove_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
