
insert into persons (name) values ('(Sin Definir)');
insert into persons (name) values ('100 Montaditos');
insert into persons (name) values ('24h No Mira a Ver');
insert into persons (name) values ('4D');
insert into persons (name) values ('5 Oceanos');
insert into persons (name) values ('6Cocos');
insert into persons (name) values ('Abuela');
insert into persons (name) values ('Abuela Carmelina');
insert into persons (name) values ('Acosta Mendez');
insert into persons (name) values ('Adagio, Sa');
insert into persons (name) values ('Adeslas');
insert into persons (name) values ('Adeslas Ale');
insert into persons (name) values ('ADL Dance');
insert into persons (name) values ('Adyen NV');
insert into persons (name) values ('AEAT');
insert into persons (name) values ('Aena Aeuropuertos');
insert into persons (name) values ('Aguacate');
insert into persons (name) values ('Aguas de Teror');
insert into persons (name) values ('Ahorros Amort. Hipoteca');
insert into persons (name) values ('Ahorros Bitdefender');
insert into persons (name) values ('Ahorros CloudMicrosoft');
insert into persons (name) values ('Ahorros CumpleAle');
insert into persons (name) values ('Ahorros CumpleCris');
insert into persons (name) values ('Ahorros CumpleRichy');
insert into persons (name) values ('Ahorros Disney');
insert into persons (name) values ('Ahorros Gym');
insert into persons (name) values ('Ahorros IBI y Basura');
insert into persons (name) values ('Ahorros ITV');
insert into persons (name) values ('Ahorros MatriculaSalle');
insert into persons (name) values ('Ahorros Medico Ale');
insert into persons (name) values ('Ahorros Quicken');
insert into persons (name) values ('Ahorros RepCasa');
insert into persons (name) values ('Ahorros RepCoche');
insert into persons (name) values ('Ahorros Reyes');
insert into persons (name) values ('Ahorros RodajeCorsa');
insert into persons (name) values ('Ahorros RodajeKona');
insert into persons (name) values ('Ahorros SeguroCorsa');
insert into persons (name) values ('Ahorros SeguroHogar');
insert into persons (name) values ('Ahorros SeguroKona');
insert into persons (name) values ('Ahorros Sillon');
insert into persons (name) values ('Ahorros UOC');
insert into persons (name) values ('Ahorros Viajes');
insert into persons (name) values ('Aida');
insert into persons (name) values ('Ainoha');
insert into persons (name) values ('AirBnB');
insert into persons (name) values ('Aitor Rox');
insert into persons (name) values ('Alcampo');
insert into persons (name) values ('Aldi');
insert into persons (name) values ('Aldo shoes');
insert into persons (name) values ('Alehop');
insert into persons (name) values ('Alejandro');
insert into persons (name) values ('Alexis');
insert into persons (name) values ('Ali Baba Kebab');
insert into persons (name) values ('AliExpress');
insert into persons (name) values ('almacenes herreros');
insert into persons (name) values ('Aloe Informatica');
insert into persons (name) values ('Altagay');
insert into persons (name) values ('Alteza');
insert into persons (name) values ('Aluminios Minor Canarias');
insert into persons (name) values ('Amalia');
insert into persons (name) values ('Amazon');
insert into persons (name) values ('American Airlines Group, Inc.');
insert into persons (name) values ('Ana Delia');
insert into persons (name) values ('Antes Muerta Que Sencilla');
insert into persons (name) values ('Antonia');
insert into persons (name) values ('Any');
insert into persons (name) values ('App Informatica');
insert into persons (name) values ('Aqualand');
insert into persons (name) values ('Aranda');
insert into persons (name) values ('Arepera Jaguey');
insert into persons (name) values ('Ariadna (Una Historia de Amor)');
insert into persons (name) values ('Arte Venecia');
insert into persons (name) values ('Asadero Manati');
insert into persons (name) values ('Asador Las Palmeras');
insert into persons (name) values ('Atelier');
insert into persons (name) values ('Atico Anaga');
insert into persons (name) values ('Aurora');
insert into persons (name) values ('Auto Laca');
insert into persons (name) values ('AutoBar');
insert into persons (name) values ('Autocentro Los Majuelos');
insert into persons (name) values ('Autoescuela La Candelaria');
insert into persons (name) values ('Autoservicio Alberto Reyes');
insert into persons (name) values ('Avon');
insert into persons (name) values ('Axa Seguros');
insert into persons (name) values ('Ayto. La Laguna');
insert into persons (name) values ('Ayto. Santa Cruz');
insert into persons (name) values ('Baby Shower');
insert into persons (name) values ('Babybu');
insert into persons (name) values ('Bahia Flamingo');
insert into persons (name) values ('Balance Adjustment');
insert into persons (name) values ('Bambini');
insert into persons (name) values ('Bar Cafeteria Eliromm');
insert into persons (name) values ('Bar Cafeteria La Plaza');
insert into persons (name) values ('Bar El Aguila');
insert into persons (name) values ('Bar El Faro');
insert into persons (name) values ('Bar Liber');
insert into persons (name) values ('Bar Piscina');
insert into persons (name) values ('Bar San Sebastian');
insert into persons (name) values ('Bar Tuto');
insert into persons (name) values ('Bar Zumeria Vitamina');
insert into persons (name) values ('Base');
insert into persons (name) values ('Basic Brand''s');
insert into persons (name) values ('BAT  Basic Attention Token');
insert into persons (name) values ('Baybu');
insert into persons (name) values ('Bazar Chino');
insert into persons (name) values ('Beautik');
insert into persons (name) values ('Belros');
insert into persons (name) values ('Berlingo Loan');
insert into persons (name) values ('Bershka');
insert into persons (name) values ('Berto y Calla');
insert into persons (name) values ('Bet365');
insert into persons (name) values ('Big Orange');
insert into persons (name) values ('Bijou Brigitte');
insert into persons (name) values ('Binary');
insert into persons (name) values ('Bitcoin (Precio en K)');
insert into persons (name) values ('Bitdefender');
insert into persons (name) values ('Bizum');
insert into persons (name) values ('Blanco');
insert into persons (name) values ('Blanco Pesca');
insert into persons (name) values ('Blizzard');
insert into persons (name) values ('BlockChain');
insert into persons (name) values ('Bocata Negro');
insert into persons (name) values ('Boda');
insert into persons (name) values ('Bodegas el Monje');
insert into persons (name) values ('Bodegas35');
insert into persons (name) values ('Bodegon Tocuyo');
insert into persons (name) values ('Bofrost');
insert into persons (name) values ('Bolivar');
insert into persons (name) values ('Bolsas de agua');
insert into persons (name) values ('BonosVip');
insert into persons (name) values ('Booking');
insert into persons (name) values ('Boutique Exagono');
insert into persons (name) values ('BP');
insert into persons (name) values ('Brave Rewards');
insert into persons (name) values ('Bruno Hernandez Leon');
insert into persons (name) values ('Buceo Seguro');
insert into persons (name) values ('Bundle Co');
insert into persons (name) values ('Burger King');
insert into persons (name) values ('Buy Recicle');
insert into persons (name) values ('Caballo Blanco');
insert into persons (name) values ('Cable Europa (Ono)');
insert into persons (name) values ('Cafat');
insert into persons (name) values ('Cafe de Pedro');
insert into persons (name) values ('Cafe Toke');
insert into persons (name) values ('Cafepan');
insert into persons (name) values ('Cafeteria Andrea');
insert into persons (name) values ('Cafeteria Brillante');
insert into persons (name) values ('Cafetería Chicho');
insert into persons (name) values ('Cafeteria Goya');
insert into persons (name) values ('Cafeteria Hospital');
insert into persons (name) values ('Cafeteria Il Divo');
insert into persons (name) values ('Cafeteria La Rotonda');
insert into persons (name) values ('Cafeteria Lumiere');
insert into persons (name) values ('Cafeteria Nolymar');
insert into persons (name) values ('Cafeteria Reineta');
insert into persons (name) values ('Cafeteria Sole');
insert into persons (name) values ('Cafeteria Tati');
insert into persons (name) values ('Cafeteria Venge');
insert into persons (name) values ('Cafeteria Zig Zag');
insert into persons (name) values ('Caixa Bank');
insert into persons (name) values ('Caja Canarias');
insert into persons (name) values ('Calcedonia');
insert into persons (name) values ('Calzedonia');
insert into persons (name) values ('Camisoteca');
insert into persons (name) values ('Campo Verde');
insert into persons (name) values ('Campsa');
insert into persons (name) values ('Canaima');
insert into persons (name) values ('CanariBat');
insert into persons (name) values ('Canarycolchon');
insert into persons (name) values ('CanaryJump');
insert into persons (name) values ('Cande');
insert into persons (name) values ('Candilas');
insert into persons (name) values ('Candy');
insert into persons (name) values ('Cantina Tenerife');
insert into persons (name) values ('Capri');
insert into persons (name) values ('Carely');
insert into persons (name) values ('Carlos');
insert into persons (name) values ('Carlos (Fisio)');
insert into persons (name) values ('Carniceria Benito Diaz');
insert into persons (name) values ('carniceria los majuelos');
insert into persons (name) values ('Carolan');
insert into persons (name) values ('Carolina Boix');
insert into persons (name) values ('Carrefour');
insert into persons (name) values ('Carrera 45 Notarios La Laguna');
insert into persons (name) values ('Cartera Naranja 10/90 FI1');
insert into persons (name) values ('Cartera Naranja 90 FI1');
insert into persons (name) values ('Casa Argelio');
insert into persons (name) values ('Casa David');
insert into persons (name) values ('Casa Pepe');
insert into persons (name) values ('Casa Peter');
insert into persons (name) values ('Casa Ricardo');
insert into persons (name) values ('Casa Santos');
insert into persons (name) values ('Casa Tomas');
insert into persons (name) values ('Casa Venezuela');
insert into persons (name) values ('Casa Venezuela (Fran)');
insert into persons (name) values ('Casa Vitorino');
insert into persons (name) values ('Casa Yeye');
insert into persons (name) values ('Cash Converters');
insert into persons (name) values ('Casi Que No');
insert into persons (name) values ('Cateteria Goya');
insert into persons (name) values ('CB Farmacia El Sobradillo');
insert into persons (name) values ('CD Tenerife');
insert into persons (name) values ('Cedisa');
insert into persons (name) values ('Centis');
insert into persons (name) values ('Centro Akoran');
insert into persons (name) values ('Centro Hipico Nueva Atalaya');
insert into persons (name) values ('Cepsa');
insert into persons (name) values ('Cerrajeria La Estrella');
insert into persons (name) values ('Cerrajeria Los Principes');
insert into persons (name) values ('Cesilio');
insert into persons (name) values ('Chafiras');
insert into persons (name) values ('Chino');
insert into persons (name) values ('Chino Shaopin');
insert into persons (name) values ('Chipi Chipi');
insert into persons (name) values ('Churreria La Gallega');
insert into persons (name) values ('Cliente RO');
insert into persons (name) values ('Clinica Denta Dr. Jorge');
insert into persons (name) values ('Clinica Dental La Gallega');
insert into persons (name) values ('Clinica Parque');
insert into persons (name) values ('Clinica Tenerife');
insert into persons (name) values ('Coelca');
insert into persons (name) values ('Coinbase');
insert into persons (name) values ('Colegio San Pablo');
insert into persons (name) values ('Colibri Bakery');
insert into persons (name) values ('Combustibles Arafo');
insert into persons (name) values ('Comercial Alvarez');
insert into persons (name) values ('Comercial Canona');
insert into persons (name) values ('Comercial chanona');
insert into persons (name) values ('Comics Food & Drink');
insert into persons (name) values ('Complejo Deportivo La Cuesta');
insert into persons (name) values ('Complejo Polvorin De Taco');
insert into persons (name) values ('Comunidad Autonoma De Canarias');
insert into persons (name) values ('Confecciones 99');
insert into persons (name) values ('Conforama');
insert into persons (name) values ('Congelados Coromoto');
insert into persons (name) values ('Congelados Tenepalma');
insert into persons (name) values ('Conipa');
insert into persons (name) values ('Contribution Towards');
insert into persons (name) values ('Contribution towards goal');
insert into persons (name) values ('Copaca');
insert into persons (name) values ('Core');
insert into persons (name) values ('Correos');
insert into persons (name) values ('Corsa Loan');
insert into persons (name) values ('Corto Maltese');
insert into persons (name) values ('CP Edif El Alfar');
insert into persons (name) values ('Crc Guajara');
insert into persons (name) values ('Creperia La Boheme');
insert into persons (name) values ('Cris');
insert into persons (name) values ('Cristi');
insert into persons (name) values ('Cristina  Profesora Ingles');
insert into persons (name) values ('Cruz Roja');
insert into persons (name) values ('Cueva Caprichosa');
insert into persons (name) values ('Cuevas Mama Antonia');
insert into persons (name) values ('Cura La Manzanilla');
insert into persons (name) values ('CyA');
insert into persons (name) values ('Da Antonio');
insert into persons (name) values ('Da Canio');
insert into persons (name) values ('Dacanio');
insert into persons (name) values ('Dagigi');
insert into persons (name) values ('Data & Asociados');
insert into persons (name) values ('David Fisio');
insert into persons (name) values ('DayPass');
insert into persons (name) values ('De Bocados');
insert into persons (name) values ('De Peques');
insert into persons (name) values ('Decathlon');
insert into persons (name) values ('Decimas');
insert into persons (name) values ('Delia');
insert into persons (name) values ('Deportes Marques');
insert into persons (name) values ('Desconocido');
insert into persons (name) values ('Desi');
insert into persons (name) values ('Desi Tattoo');
insert into persons (name) values ('DG Eventos');
insert into persons (name) values ('DGT');
insert into persons (name) values ('Dicane');
insert into persons (name) values ('Diego');
insert into persons (name) values ('Dinosol');
insert into persons (name) values ('Disa');
insert into persons (name) values ('Disa El Sobradillo');
insert into persons (name) values ('Disney');
insert into persons (name) values ('Disney+');
insert into persons (name) values ('Distribución de Ahorros');
insert into persons (name) values ('Distrimar');
insert into persons (name) values ('DK Modas');
insert into persons (name) values ('Domingo Alonso Group');
insert into persons (name) values ('Don Comelon');
insert into persons (name) values ('Don Manuel');
insert into persons (name) values ('Don Mineral');
insert into persons (name) values ('Don Pollo');
insert into persons (name) values ('Donde Bibi');
insert into persons (name) values ('Doña');
insert into persons (name) values ('Doña Pata');
insert into persons (name) values ('Douglas');
insert into persons (name) values ('Dr Olivera');
insert into persons (name) values ('Drago Park');
insert into persons (name) values ('Dragut Kebab');
insert into persons (name) values ('Dulceria Butterfly');
insert into persons (name) values ('Dulceria Diaz');
insert into persons (name) values ('E.S. Bp');
insert into persons (name) values ('E.S. El Bohio');
insert into persons (name) values ('E.S. El Chorrillo');
insert into persons (name) values ('E.S. El Mirador');
insert into persons (name) values ('E.S. El Poris');
insert into persons (name) values ('E.S. Icod De Los Vinos');
insert into persons (name) values ('E.S. Las Chumberas');
insert into persons (name) values ('E.s. Los Majuelos');
insert into persons (name) values ('E.S. Shell Arona');
insert into persons (name) values ('Ebay');
insert into persons (name) values ('Ekina Weyler');
insert into persons (name) values ('El Aguila');
insert into persons (name) values ('El Ba');
insert into persons (name) values ('El Bodegon Gomero');
insert into persons (name) values ('El Bohio');
insert into persons (name) values ('El Brezo');
insert into persons (name) values ('El Buda Goloso');
insert into persons (name) values ('El Buen Paladar');
insert into persons (name) values ('El Caminante');
insert into persons (name) values ('El Cañonazo');
insert into persons (name) values ('El Capricho');
insert into persons (name) values ('El Chollo Del Neumatico');
insert into persons (name) values ('El Colgadizo');
insert into persons (name) values ('El Comedor');
insert into persons (name) values ('El Congreso');
insert into persons (name) values ('El Cordero');
insert into persons (name) values ('El Corte Ingles');
insert into persons (name) values ('El Corte Ingles Oportunidades');
insert into persons (name) values ('El Cubano');
insert into persons (name) values ('El Gato Goloso');
insert into persons (name) values ('El Kilo');
insert into persons (name) values ('El Mirador');
insert into persons (name) values ('El Mundo del Pintor');
insert into persons (name) values ('El Negro Mario');
insert into persons (name) values ('El Numero');
insert into persons (name) values ('El Obrador de La Laguna');
insert into persons (name) values ('El Obrador del Sobradillo');
insert into persons (name) values ('El Paso 2000');
insert into persons (name) values ('El Perrito Roquero');
insert into persons (name) values ('El Pollito');
insert into persons (name) values ('El pollo abrasado');
insert into persons (name) values ('El Rancho De Nino');
insert into persons (name) values ('El Rancho Texas');
insert into persons (name) values ('El Rayo');
insert into persons (name) values ('El Rincon Brazile');
insert into persons (name) values ('El Rincon de San Diego');
insert into persons (name) values ('El Rincon Gomero');
insert into persons (name) values ('El Stand');
insert into persons (name) values ('El Sue');
insert into persons (name) values ('El Turpial');
insert into persons (name) values ('Electrodomesticos Tenerife');
insert into persons (name) values ('Electronica Radio Lax');
insert into persons (name) values ('Elsa');
insert into persons (name) values ('Elyman');
insert into persons (name) values ('Emmasa');
insert into persons (name) values ('Encuentro');
insert into persons (name) values ('Endesa');
insert into persons (name) values ('English101');
insert into persons (name) values ('Entrechemas');
insert into persons (name) values ('Entreflores');
insert into persons (name) values ('Equivalenza');
insert into persons (name) values ('ES BP Tacoronte');
insert into persons (name) values ('ES Los Andenes');
insert into persons (name) values ('Escuela Oficial De Idiomas');
insert into persons (name) values ('Esquina Weyler');
insert into persons (name) values ('Esta Rico');
insert into persons (name) values ('ETAM');
insert into persons (name) values ('Eureka Kids');
insert into persons (name) values ('Eva');
insert into persons (name) values ('Extreme Sport');
insert into persons (name) values ('Fabiana');
insert into persons (name) values ('Farmacia');
insert into persons (name) values ('Farmacia Antonio');
insert into persons (name) values ('farmacia Avda la lib');
insert into persons (name) values ('Farmacia Avda Libertad');
insert into persons (name) values ('Farmacia Basilio Valladares');
insert into persons (name) values ('Farmacia Camino La Laguna');
insert into persons (name) values ('Farmacia Carmen Estrellos');
insert into persons (name) values ('Farmacia Coromina');
insert into persons (name) values ('Farmacia Durana Santa Cruz Dees');
insert into persons (name) values ('Farmacia El Camin');
insert into persons (name) values ('farmacia fdo rguez');
insert into persons (name) values ('Farmacia Finca Espa');
insert into persons (name) values ('Farmacia Icod De Los Vinos');
insert into persons (name) values ('Farmacia Jose Ignacio');
insert into persons (name) values ('farmacia las canteras');
insert into persons (name) values ('Farmacia Los Majuelos');
insert into persons (name) values ('farmacia Luisa Garcia');
insert into persons (name) values ('Farmacia Maria An');
insert into persons (name) values ('Farmacia Maria Antonia');
insert into persons (name) values ('farmacia miguel r');
insert into persons (name) values ('Farmacia San Bartolomes');
insert into persons (name) values ('Farmacia Sanchez Gijon');
insert into persons (name) values ('Farmacia Trinidad');
insert into persons (name) values ('Farmacia Triviño');
insert into persons (name) values ('Farnacia Martin Neda');
insert into persons (name) values ('Feboda');
insert into persons (name) values ('Felipe');
insert into persons (name) values ('Fenix Directo');
insert into persons (name) values ('Feria Santa Cruz');
insert into persons (name) values ('Fernando Gonzalez');
insert into persons (name) values ('Ferrediaz');
insert into persons (name) values ('Ferreteria');
insert into persons (name) values ('Ferreteria Canaria');
insert into persons (name) values ('Ferreteria Chavez');
insert into persons (name) values ('Ferreteria La Llave');
insert into persons (name) values ('Ferreteria Ramon');
insert into persons (name) values ('Ferreteria San Bartolome');
insert into persons (name) values ('Ferretodo');
insert into persons (name) values ('Fettuccine Restaurante');
insert into persons (name) values ('Fica El Carreton');
insert into persons (name) values ('Figaro');
insert into persons (name) values ('Fini Del Castillo');
insert into persons (name) values ('Fisio Javier');
insert into persons (name) values ('Flamenca');
insert into persons (name) values ('Floristeria');
insert into persons (name) values ('Floristeria Flor');
insert into persons (name) values ('Floristeria Lara');
insert into persons (name) values ('Floristeria Maria');
insert into persons (name) values ('FNMT');
insert into persons (name) values ('Fogon Cho Edu');
insert into persons (name) values ('Folder');
insert into persons (name) values ('Fondo Cartera Naranja 75/251');
insert into persons (name) values ('Fondo Fidelity World ING');
insert into persons (name) values ('Fondo Fidelity World ING1');
insert into persons (name) values ('Fondo Naranja Conservador1');
insert into persons (name) values ('Fondo Naranja Dinamico1');
insert into persons (name) values ('Fondo Naranja Ibex351');
insert into persons (name) values ('Fondo Naranja Moderado1');
insert into persons (name) values ('Fondo Naranja Renta Fija1');
insert into persons (name) values ('Ford Motor CO');
insert into persons (name) values ('Formacion Sol');
insert into persons (name) values ('Foto Club');
insert into persons (name) values ('Foto Joven');
insert into persons (name) values ('Foto Travel');
insert into persons (name) values ('Fotomaton');
insert into persons (name) values ('Francisco Nortennio');
insert into persons (name) values ('Fred Olsen');
insert into persons (name) values ('Freeware Soluciones Empresariales');
insert into persons (name) values ('Freshly Cosmetic Reus');
insert into persons (name) values ('FrikiYo');
insert into persons (name) values ('Fruteria');
insert into persons (name) values ('Fruteria Don Melon');
insert into persons (name) values ('Fruteria La Finca');
insert into persons (name) values ('Fruteria Los Olivos');
insert into persons (name) values ('Fruteria Teimila');
insert into persons (name) values ('Fundacion Josep Carreras');
insert into persons (name) values ('Fusion Burger');
insert into persons (name) values ('Galerias Laguna');
insert into persons (name) values ('Game');
insert into persons (name) values ('Garcia Galeano, Miguel Alejandro');
insert into persons (name) values ('Garcia Y Correa');
insert into persons (name) values ('Garriga');
insert into persons (name) values ('Generali');
insert into persons (name) values ('Generaltickets');
insert into persons (name) values ('Gimnacio San Benito');
insert into persons (name) values ('Gimnacio Tagoror');
insert into persons (name) values ('Ginecologia Dr Trabado');
insert into persons (name) values ('Globo');
insert into persons (name) values ('Gobierno De Canarias');
insert into persons (name) values ('Goin');
insert into persons (name) values ('Goin Inversion');
insert into persons (name) values ('Gomez Asesores');
insert into persons (name) values ('Good For You');
insert into persons (name) values ('Google');
insert into persons (name) values ('Gorrita');
insert into persons (name) values ('Granier');
insert into persons (name) values ('Greenjet');
insert into persons (name) values ('Groupon');
insert into persons (name) values ('Grupo BC');
insert into persons (name) values ('Grupo NK Automocion');
insert into persons (name) values ('Guachinche casa san antonio');
insert into persons (name) values ('Guachinche Como en Casa');
insert into persons (name) values ('Guachinche Ctra. Vieja');
insert into persons (name) values ('Guachinche El Deposito');
insert into persons (name) values ('Guachinche El Fonil');
insert into persons (name) values ('Guachinche La Palmera');
insert into persons (name) values ('Guachinche Uva Negra');
insert into persons (name) values ('Guarapo');
insert into persons (name) values ('H&M');
insert into persons (name) values ('H2O Quality System');
insert into persons (name) values ('Hacienda');
insert into persons (name) values ('Happy Phone');
insert into persons (name) values ('HBO España');
insert into persons (name) values ('Heladeria El Gloton');
insert into persons (name) values ('Heladeria El Sueño');
insert into persons (name) values ('Heladeria La Fragola');
insert into persons (name) values ('Hennes');
insert into persons (name) values ('Herbodietetica Alcampo');
insert into persons (name) values ('Hesperides');
insert into persons (name) values ('Hierbas Salvajes');
insert into persons (name) values ('Hiperdino');
insert into persons (name) values ('Hiperjuguetes');
insert into persons (name) values ('Hipertrebol');
insert into persons (name) values ('Hipoteca Caixa');
insert into persons (name) values ('Hipoteca Caixa (Empresa)');
insert into persons (name) values ('Hipoteca Casa');
insert into persons (name) values ('Hispamer');
insert into persons (name) values ('Hogaria');
insert into persons (name) values ('Horno Del Pan');
insert into persons (name) values ('Hospital La Candelaria');
insert into persons (name) values ('Hospiten Rambla');
insert into persons (name) values ('Hostal La Fonda');
insert into persons (name) values ('Hotel Alif Campo Pequeño');
insert into persons (name) values ('Hotel Barcelo Santiago');
insert into persons (name) values ('Hotel Barcelo Varadero');
insert into persons (name) values ('Hotel Joao Padeiro');
insert into persons (name) values ('Hotel Las Holas');
insert into persons (name) values ('Hotelbeds');
insert into persons (name) values ('HyM');
insert into persons (name) values ('I.E.S. Cesar Manrique');
insert into persons (name) values ('Iberdrola');
insert into persons (name) values ('Iciesa');
insert into persons (name) values ('Icodence');
insert into persons (name) values ('IES La Laboral');
insert into persons (name) values ('Igueste Petroleos');
insert into persons (name) values ('Ikea');
insert into persons (name) values ('Ikea Family');
insert into persons (name) values ('ilunion');
insert into persons (name) values ('Imagen Pro');
insert into persons (name) values ('Ind. Juno');
insert into persons (name) values ('Ing Direct');
insert into persons (name) values ('ING Direct  Euro Stoxx 501');
insert into persons (name) values ('Ing Direct Fn Ibex 35 Fi');
insert into persons (name) values ('ING DIRECT S&P 5001');
insert into persons (name) values ('ING Plan 2050');
insert into persons (name) values ('Inmobiliaria Continental');
insert into persons (name) values ('Innova Kids');
insert into persons (name) values ('Inside Tenerife');
insert into persons (name) values ('Instituto');
insert into persons (name) values ('Insular Dietetica');
insert into persons (name) values ('Interjuguetes');
insert into persons (name) values ('ISAAC');
insert into persons (name) values ('Isabel Martin (Fruteria Los majuelos)');
insert into persons (name) values ('Isabel Martin (Fruteria)');
insert into persons (name) values ('ITV');
insert into persons (name) values ('ITV Santa Cruz');
insert into persons (name) values ('Ivan Rotonda');
insert into persons (name) values ('Ives Rocher');
insert into persons (name) values ('J4');
insert into persons (name) values ('Jacaranda');
insert into persons (name) values ('Jack Jones');
insert into persons (name) values ('Jalea De Menta');
insert into persons (name) values ('Jardines Madre del Agua');
insert into persons (name) values ('Jhonjil');
insert into persons (name) values ('JJ Motor');
insert into persons (name) values ('JMD Cerrajeria');
insert into persons (name) values ('Joel');
insert into persons (name) values ('Joisa');
insert into persons (name) values ('Joma Peluqueros');
insert into persons (name) values ('Jorge OMN');
insert into persons (name) values ('Jose Masajista');
insert into persons (name) values ('Joyeria Jose Luis');
insert into persons (name) values ('Joyeria Lexly');
insert into persons (name) values ('Juan Carlos');
insert into persons (name) values ('Jufer Peluqueros');
insert into persons (name) values ('Jugueteria El Primero');
insert into persons (name) values ('Jungle Park');
insert into persons (name) values ('Kaffa Sugar');
insert into persons (name) values ('Kaos');
insert into persons (name) values ('Karting La Esperanza');
insert into persons (name) values ('Karuna');
insert into persons (name) values ('Ketay Travel');
insert into persons (name) values ('KFC');
insert into persons (name) values ('Kiabi');
insert into persons (name) values ('Kiara Xuxes');
insert into persons (name) values ('Kiko');
insert into persons (name) values ('Kiosco La Plaza');
insert into persons (name) values ('Kiosko');
insert into persons (name) values ('Kiosko Manolo');
insert into persons (name) values ('Kit Cash');
insert into persons (name) values ('Kiwoko');
insert into persons (name) values ('Koala');
insert into persons (name) values ('La Barrera');
insert into persons (name) values ('La Bohemia');
insert into persons (name) values ('La Casa de La Raqueta');
insert into persons (name) values ('La Casa del Baoba');
insert into persons (name) values ('La Casa Del Mar');
insert into persons (name) values ('La Casa Del Pescado');
insert into persons (name) values ('La casa.del terror');
insert into persons (name) values ('La caseta');
insert into persons (name) values ('La Casona');
insert into persons (name) values ('La Cayena');
insert into persons (name) values ('La Cuadra del Palmero');
insert into persons (name) values ('La Duquesa');
insert into persons (name) values ('La Folie');
insert into persons (name) values ('La Garriga');
insert into persons (name) values ('La Hucha');
insert into persons (name) values ('La Huerta de Ana y Eva');
insert into persons (name) values ('La Llovizna');
insert into persons (name) values ('La Masa Pastelera');
insert into persons (name) values ('La Ocasion');
insert into persons (name) values ('La Panoteca');
insert into persons (name) values ('La Perla');
insert into persons (name) values ('La Pizzeta');
insert into persons (name) values ('La Restaurante La Charca');
insert into persons (name) values ('La Rotonda');
insert into persons (name) values ('La Salle La Laguna');
insert into persons (name) values ('La Sifoneria');
insert into persons (name) values ('La Suite');
insert into persons (name) values ('La Sureña');
insert into persons (name) values ('La Taberna');
insert into persons (name) values ('La Tacita De Barro');
insert into persons (name) values ('La Taqueria');
insert into persons (name) values ('La Tarteria');
insert into persons (name) values ('La Tasquita De Mami');
insert into persons (name) values ('La Tasquita Del Puerto');
insert into persons (name) values ('La Tronja');
insert into persons (name) values ('Laboratorio');
insert into persons (name) values ('Laboratorios Negrin');
insert into persons (name) values ('Lalo');
insert into persons (name) values ('Laly Del Castillo');
insert into persons (name) values ('Lalyflor');
insert into persons (name) values ('Las Hierbas De La Recoba');
insert into persons (name) values ('Las hierbas salvajes');
insert into persons (name) values ('Las Rosas');
insert into persons (name) values ('Las Terrazas Del Sauzal');
insert into persons (name) values ('Learning Centre');
insert into persons (name) values ('Lefties');
insert into persons (name) values ('Lekkery');
insert into persons (name) values ('Leroy Merlin');
insert into persons (name) values ('LetyShop');
insert into persons (name) values ('Libertad');
insert into persons (name) values ('Libreria Carlin');
insert into persons (name) values ('Libreria La Isla');
insert into persons (name) values ('Libreria Lemus');
insert into persons (name) values ('Libreria Tenifer');
insert into persons (name) values ('Lidia');
insert into persons (name) values ('Lidl');
insert into persons (name) values ('Lifer');
insert into persons (name) values ('Linea Directa');
insert into persons (name) values ('Link Soluciones');
insert into persons (name) values ('Lokura');
insert into persons (name) values ('Lokura El Sobradillo');
insert into persons (name) values ('Lolo');
insert into persons (name) values ('Loly Cash');
insert into persons (name) values ('Loops And Coffe');
insert into persons (name) values ('Lopez Echeto');
insert into persons (name) values ('Loro Parque');
insert into persons (name) values ('Los Garrafones');
insert into persons (name) values ('Losteria Del Greco');
insert into persons (name) values ('Loterias Y Apuestas Del Estado');
insert into persons (name) values ('Loverde (Lactancia)');
insert into persons (name) values ('Luna');
insert into persons (name) values ('Luz Hogar Tenerife');
insert into persons (name) values ('Macdalena');
insert into persons (name) values ('Macy''s, INC');
insert into persons (name) values ('Madre Luna');
insert into persons (name) values ('Mael Telecomunicaciones');
insert into persons (name) values ('Magenta');
insert into persons (name) values ('Majarete');
insert into persons (name) values ('Makika CO');
insert into persons (name) values ('Makro');
insert into persons (name) values ('Mama');
insert into persons (name) values ('Mango');
insert into persons (name) values ('Manocar');
insert into persons (name) values ('Manolo');
insert into persons (name) values ('Mapfre');
insert into persons (name) values ('Mar y Lluvia');
insert into persons (name) values ('Marcos Peluquero');
insert into persons (name) values ('Maria (rezados)');
insert into persons (name) values ('Maria Del Mar');
insert into persons (name) values ('market Stear Adeje');
insert into persons (name) values ('Maroparque');
insert into persons (name) values ('Marypaz');
insert into persons (name) values ('Masquebio');
insert into persons (name) values ('Maxi Market');
insert into persons (name) values ('Maximarket');
insert into persons (name) values ('MaxiPizza');
insert into persons (name) values ('Maya');
insert into persons (name) values ('Mayoral');
insert into persons (name) values ('Mcdonald');
insert into persons (name) values ('Media Markt');
insert into persons (name) values ('Melania');
insert into persons (name) values ('Mercadillo de Tegueste');
insert into persons (name) values ('Mercado Agricultor La Guancha');
insert into persons (name) values ('Mercado De La Laguna');
insert into persons (name) values ('Mercadona');
insert into persons (name) values ('Mercafruta Goyo');
insert into persons (name) values ('Mercedes');
insert into persons (name) values ('Meridiano Bulebar');
insert into persons (name) values ('Mesa Y Honorio');
insert into persons (name) values ('Metropolitano de TFE');
insert into persons (name) values ('MGI');
insert into persons (name) values ('MGuerra');
insert into persons (name) values ('Mi Consentida');
insert into persons (name) values ('Mi Perrito');
insert into persons (name) values ('Microsft');
insert into persons (name) values ('Microsoft');
insert into persons (name) values ('Mil Arepas');
insert into persons (name) values ('Milkshakes Moo''s');
insert into persons (name) values ('Mimi');
insert into persons (name) values ('MIMO');
insert into persons (name) values ('Minimarket El Sobradillo');
insert into persons (name) values ('Minimarket San Sebastian');
insert into persons (name) values ('Minit Spain');
insert into persons (name) values ('Mintos');
insert into persons (name) values ('Mio Gelato');
insert into persons (name) values ('Mio Helado');
insert into persons (name) values ('Mirian');
insert into persons (name) values ('Misako');
insert into persons (name) values ('Mister Mint');
insert into persons (name) values ('Mister Smile');
insert into persons (name) values ('Moderna, Inc');
insert into persons (name) values ('Moises Osteopata');
insert into persons (name) values ('MoneyUp');
insert into persons (name) values ('Monica');
insert into persons (name) values ('Mordisquitos El Medano');
insert into persons (name) values ('Mr Smile');
insert into persons (name) values ('Mr Snack');
insert into persons (name) values ('MSCI World, Net Return');
insert into persons (name) values ('Mucha Brasa');
insert into persons (name) values ('Multicines Tenerife');
insert into persons (name) values ('Multidulce');
insert into persons (name) values ('Multienda Angelitos');
insert into persons (name) values ('Multimarket 24 Mk');
insert into persons (name) values ('MultiOpticas');
insert into persons (name) values ('Multiopticas Orotava');
insert into persons (name) values ('Multiprecios La Cuesta');
insert into persons (name) values ('Multitienda Avenida');
insert into persons (name) values ('Multitienda Olympo');
insert into persons (name) values ('Multitienda principe');
insert into persons (name) values ('Multitienda Trancas y Barrancas');
insert into persons (name) values ('Mundo Ahorro');
insert into persons (name) values ('Mundo Vegetal');
insert into persons (name) values ('Museo Ciencia y El Cosmo');
insert into persons (name) values ('MusgoPiel');
insert into persons (name) values ('Musicanarias');
insert into persons (name) values ('Mussgo Piel');
insert into persons (name) values ('Mutuafondo Renta Fija Flexible I1');
insert into persons (name) values ('Muy Mucho');
insert into persons (name) values ('My Coset Taco');
insert into persons (name) values ('Naguara');
insert into persons (name) values ('Nalber');
insert into persons (name) values ('NartexSoftware');
insert into persons (name) values ('Nationale Nederlanden');
insert into persons (name) values ('Natura');
insert into persons (name) values ('Natural Burger');
insert into persons (name) values ('Nautico Santa Cruz');
insert into persons (name) values ('Naviera Armas');
insert into persons (name) values ('Netflix');
insert into persons (name) values ('Neumaticos Atlantico');
insert into persons (name) values ('New Yorker');
insert into persons (name) values ('NG bailadores');
insert into persons (name) values ('Nikki Jugueterias');
insert into persons (name) values ('Nimeria Comics');
insert into persons (name) values ('Ninety Nine');
insert into persons (name) values ('Noah Home');
insert into persons (name) values ('Noelia');
insert into persons (name) values ('Nomi');
insert into persons (name) values ('Notaria Beatriz Eugenia Cabello Mestres');
insert into persons (name) values ('Novias Isabel');
insert into persons (name) values ('Numero 1');
insert into persons (name) values ('NutriSport');
insert into persons (name) values ('ONCE');
insert into persons (name) values ('One Way');
insert into persons (name) values ('Opening Balance');
insert into persons (name) values ('Opening Cash Balance');
insert into persons (name) values ('Optica Cosmos');
insert into persons (name) values ('OroroTV');
insert into persons (name) values ('Orvecame');
insert into persons (name) values ('Osteofisio Weyler');
insert into persons (name) values ('Paco Martinez');
insert into persons (name) values ('Padres');
insert into persons (name) values ('Palmelita');
insert into persons (name) values ('Panaria');
insert into persons (name) values ('Panoteca');
insert into persons (name) values ('Papa');
insert into persons (name) values ('Parador Del Teide');
insert into persons (name) values ('Parfois');
insert into persons (name) values ('Parking');
insert into persons (name) values ('Parking Candelaria');
insert into persons (name) values ('Parking Deportivo Radazul');
insert into persons (name) values ('Parking Edif.  Rodadero');
insert into persons (name) values ('Parking Edif. Rodadero');
insert into persons (name) values ('Parking El Cristo');
insert into persons (name) values ('Parking El Pilar');
insert into persons (name) values ('Parking Hospital');
insert into persons (name) values ('Parking Intercambiador');
insert into persons (name) values ('Parking La Laguna');
insert into persons (name) values ('Parking Las Piramides');
insert into persons (name) values ('Parking Mencey');
insert into persons (name) values ('Parking Puerto Deportivo Radazuk');
insert into persons (name) values ('Parking Ramon y Cajal');
insert into persons (name) values ('Parking Recreativo Inversiones Parque');
insert into persons (name) values ('Parking Tenerife');
insert into persons (name) values ('Parking Torviscas');
insert into persons (name) values ('Parking Trinidad');
insert into persons (name) values ('Parking Weyler');
insert into persons (name) values ('Party Fiesta');
insert into persons (name) values ('Pasteleria Diaz');
insert into persons (name) values ('Paula Yasmi');
insert into persons (name) values ('Paypal');
insert into persons (name) values ('Pcan');
insert into persons (name) values ('Pediatra Antonio Dominguez');
insert into persons (name) values ('Pegaso APP');
insert into persons (name) values ('Peluqueria Chip');
insert into persons (name) values ('Peluqueria Diego');
insert into persons (name) values ('Peluqueria JOMA');
insert into persons (name) values ('Peluqueria raju');
insert into persons (name) values ('Peluqueria Vencia');
insert into persons (name) values ('Peluqueria Venecia');
insert into persons (name) values ('Penedo');
insert into persons (name) values ('Perez Brito Alimentacion');
insert into persons (name) values ('Perritos La Concepcion');
insert into persons (name) values ('Pescamar');
insert into persons (name) values ('Pfzier');
insert into persons (name) values ('PIMCO GIS Commodity Real Return1');
insert into persons (name) values ('Pineda');
insert into persons (name) values ('Pinkie');
insert into persons (name) values ('Piscina Municipal');
insert into persons (name) values ('Pizzaburger Eltres');
insert into persons (name) values ('Pizzeria Da Angelo');
insert into persons (name) values ('Pizzeria Da Giulio');
insert into persons (name) values ('PlimPlim');
insert into persons (name) values ('Policia Nacional');
insert into persons (name) values ('Popoen Merceria');
insert into persons (name) values ('Prenatal');
insert into persons (name) values ('Presto Pizza');
insert into persons (name) values ('Primark');
insert into persons (name) values ('Primor');
insert into persons (name) values ('Priscila');
insert into persons (name) values ('Producciones NET');
insert into persons (name) values ('Proitesa');
insert into persons (name) values ('PTmo Ana');
insert into persons (name) values ('Ptmo Ayuda Ana');
insert into persons (name) values ('Ptmo Caixa 7187');
insert into persons (name) values ('Ptmo ING (Kona)');
insert into persons (name) values ('Ptmo ING 0022 (Ana)');
insert into persons (name) values ('Ptmo ING 0866 (Muebles)');
insert into persons (name) values ('PTMO ING 0866 Muebles');
insert into persons (name) values ('Ptmo ING 5179 (Ana3)');
insert into persons (name) values ('Ptmo ING 5466');
insert into persons (name) values ('Ptmo Santander 0917');
insert into persons (name) values ('Puertas Automaticas');
insert into persons (name) values ('Pull And Bear');
insert into persons (name) values ('Que sabroson');
insert into persons (name) values ('Quicken');
insert into persons (name) values ('Quimera Sub');
insert into persons (name) values ('Quinielista');
insert into persons (name) values ('Radevi');
insert into persons (name) values ('Radio Taxi');
insert into persons (name) values ('Rakuten TV');
insert into persons (name) values ('Rancho Arizona');
insert into persons (name) values ('RASCA RASCA ONCE');
insert into persons (name) values ('Real Musical');
insert into persons (name) values ('Reale Seguros');
insert into persons (name) values ('Realle Seguros');
insert into persons (name) values ('Rebelde');
insert into persons (name) values ('Recambios Valladares');
insert into persons (name) values ('Recinto Ferial');
insert into persons (name) values ('Recreativos Alcampo');
insert into persons (name) values ('Recreativos Pineda');
insert into persons (name) values ('Regalitos');
insert into persons (name) values ('Repsol');
insert into persons (name) values ('Residencia');
insert into persons (name) values ('Resraurante La Ermita');
insert into persons (name) values ('Rest. Chino Fun Ding');
insert into persons (name) values ('Rest. Como en Casa');
insert into persons (name) values ('Rest. Da Vinci');
insert into persons (name) values ('Rest. La Badana');
insert into persons (name) values ('Rest. La Morenita');
insert into persons (name) values ('Rest. Las Tradiciones');
insert into persons (name) values ('Rest. Verona');
insert into persons (name) values ('Rest. Xanadu');
insert into persons (name) values ('Restaurante Aguamansa');
insert into persons (name) values ('Restaurante Casa Domingo');
insert into persons (name) values ('Restaurante China Town');
insert into persons (name) values ('Restaurante El Fronton');
insert into persons (name) values ('Restaurante El Junquito');
insert into persons (name) values ('Restaurante El Manantial');
insert into persons (name) values ('Restaurante El Mirador');
insert into persons (name) values ('Restaurante El Molino');
insert into persons (name) values ('Restaurante El Pariente');
insert into persons (name) values ('Restaurante El Tunel');
insert into persons (name) values ('Restaurante Garcia');
insert into persons (name) values ('Restaurante La Kasona');
insert into persons (name) values ('Restaurante Las Rosas');
insert into persons (name) values ('Restaurante Las Tradiciones');
insert into persons (name) values ('Restaurante Los Almendros');
insert into persons (name) values ('REstaurante Los Arroyos');
insert into persons (name) values ('Restaurante Los Pinos');
insert into persons (name) values ('Restaurante Mas que Carne');
insert into persons (name) values ('Restaurante Melian');
insert into persons (name) values ('Restaurante San Pancracio');
insert into persons (name) values ('Restaurante Turco');
insert into persons (name) values ('Restocan 2013');
insert into persons (name) values ('Rgzo F/Datos');
insert into persons (name) values ('Rhodani');
insert into persons (name) values ('Ricky''s');
insert into persons (name) values ('Ricon El Sapito');
insert into persons (name) values ('Rilylab');
insert into persons (name) values ('RKS');
insert into persons (name) values ('RO Del Castillo');
insert into persons (name) values ('Rocas Gabinete');
insert into persons (name) values ('Rocasa');
insert into persons (name) values ('Rocio');
insert into persons (name) values ('Rocio y Diego');
insert into persons (name) values ('Rockanroll Baby');
insert into persons (name) values ('Rosetta Stone');
insert into persons (name) values ('Rosi Capazo');
insert into persons (name) values ('Rosy');
insert into persons (name) values ('Roxana');
insert into persons (name) values ('Royal Tenerife Country');
insert into persons (name) values ('Rugantino');
insert into persons (name) values ('RY Peluqueras');
insert into persons (name) values ('Sacs');
insert into persons (name) values ('Sada Canarias');
insert into persons (name) values ('Sagrera Canarias');
insert into persons (name) values ('Salinas Fuencaliente');
insert into persons (name) values ('Sanavadit');
insert into persons (name) values ('Santander Consumer');
insert into persons (name) values ('Saturn');
insert into persons (name) values ('Scaffos Peluqueros');
insert into persons (name) values ('Scooter');
insert into persons (name) values ('Securitas Direct');
insert into persons (name) values ('Seguridad Social');
insert into persons (name) values ('Servicio Canario De Empleo');
insert into persons (name) values ('Servicio Canario Salud');
insert into persons (name) values ('sestife');
insert into persons (name) values ('Sfera');
insert into persons (name) values ('Shan Oriental');
insert into persons (name) values ('Shana');
insert into persons (name) values ('Shein');
insert into persons (name) values ('Shell');
insert into persons (name) values ('Sibora Mar');
insert into persons (name) values ('Siemens');
insert into persons (name) values ('Sin Espinas');
insert into persons (name) values ('Sinpromi SL');
insert into persons (name) values ('Sofican');
insert into persons (name) values ('Soi Complementos');
insert into persons (name) values ('Sole y Aranda');
insert into persons (name) values ('SpainToner');
insert into persons (name) values ('Spar');
insert into persons (name) values ('Springfield');
insert into persons (name) values ('Sprinter');
insert into persons (name) values ('Stadio Sport');
insert into persons (name) values ('Starfit');
insert into persons (name) values ('Stikets');
insert into persons (name) values ('Stradivarius');
insert into persons (name) values ('Sultan Kebab');
insert into persons (name) values ('Sunset');
insert into persons (name) values ('Supermarket Stear Adeje');
insert into persons (name) values ('Supermercado El Parque');
insert into persons (name) values ('Supermercado Las Mercedes');
insert into persons (name) values ('Syncrom Informatica, Sl');
insert into persons (name) values ('Taller de Motos Carlos');
insert into persons (name) values ('Taller Motorland');
insert into persons (name) values ('Taller Tic Tac');
insert into persons (name) values ('Tasca Alavasca');
insert into persons (name) values ('Tasca Canana');
insert into persons (name) values ('Tasca Honorii');
insert into persons (name) values ('Tasca La Muralla');
insert into persons (name) values ('Tasiri');
insert into persons (name) values ('Tea & Baking');
insert into persons (name) values ('TecnoOulet');
insert into persons (name) values ('Telepizza');
insert into persons (name) values ('Teletoy');
insert into persons (name) values ('Ten+');
insert into persons (name) values ('Tenerife FC');
insert into persons (name) values ('Terraza Parque');
insert into persons (name) values ('Terrazas del Sauzal');
insert into persons (name) values ('Texaco');
insert into persons (name) values ('Texaco El Sobradill');
insert into persons (name) values ('Tezenis');
insert into persons (name) values ('TGas');
insert into persons (name) values ('The Boeing Co.');
insert into persons (name) values ('Tia Ana');
insert into persons (name) values ('TikTok');
insert into persons (name) values ('Tinerdanza');
insert into persons (name) values ('Tino');
insert into persons (name) values ('Tio Chuchi');
insert into persons (name) values ('Titsa');
insert into persons (name) values ('To Go');
insert into persons (name) values ('Todogar');
insert into persons (name) values ('TodoMotos');
insert into persons (name) values ('Tomas');
insert into persons (name) values ('TomaTicket');
insert into persons (name) values ('Tony Romas');
insert into persons (name) values ('ToysRus');
insert into persons (name) values ('Tramas');
insert into persons (name) values ('Traspaso');
insert into persons (name) values ('Traspaso A Gtos');
insert into persons (name) values ('Traspaso Ahorros');
insert into persons (name) values ('Traspaso Efectivo Garaje');
insert into persons (name) values ('Traspaso Guardar Amortizacion Hipoteca');
insert into persons (name) values ('Traspaso Paypal Disney');
insert into persons (name) values ('Traspaso Paypal Nube Madre');
insert into persons (name) values ('Traspaso Paypal Nube Nuestra');
insert into persons (name) values ('Udemy');
insert into persons (name) values ('Ulices');
insert into persons (name) values ('Umbrella It');
insert into persons (name) values ('Under Armour, INC.');
insert into persons (name) values ('Uned');
insert into persons (name) values ('Universidad De La Laguna');
insert into persons (name) values ('Universitat Oberta De Catalunya');
insert into persons (name) values ('Urbanismo');
insert into persons (name) values ('Ventajon');
insert into persons (name) values ('Video Trabel');
insert into persons (name) values ('Visanta');
insert into persons (name) values ('Vital Gym');
insert into persons (name) values ('Vital Joyas');
insert into persons (name) values ('Vital Joyas Canarias');
insert into persons (name) values ('Vivenatura');
insert into persons (name) values ('Vodafone');
insert into persons (name) values ('Vontobel Fund - Emerging Markets1');
insert into persons (name) values ('Wacom');
insert into persons (name) values ('Watch It');
insert into persons (name) values ('Whatsapp');
insert into persons (name) values ('White Miracle Jeweller');
insert into persons (name) values ('Willy');
insert into persons (name) values ('Withdrawal from goal');
insert into persons (name) values ('Xanadu');
insert into persons (name) values ('XTI');
insert into persons (name) values ('Yani');
insert into persons (name) values ('Yani y Dacil');
insert into persons (name) values ('Yasmin Peluqueras');
insert into persons (name) values ('Yasmina');
insert into persons (name) values ('Yayi');
insert into persons (name) values ('Yazztel');
insert into persons (name) values ('Yelmo Cineplex');
insert into persons (name) values ('Yelmo Cines');
insert into persons (name) values ('Yeray');
insert into persons (name) values ('Yoigo');
insert into persons (name) values ('Yurena afonso');
insert into persons (name) values ('Zapatero');
insert into persons (name) values ('Zara');
insert into persons (name) values ('Zarpa');
insert into persons (name) values ('Zepelin');
insert into persons (name) values ('Zeppelin');
insert into persons (name) values ('Zipi y Zape');
insert into persons (name) values ('Zona Motos');
insert into persons (name) values ('Zumeria Vitamina');

