insert into categories (id, description, categoriesTypesid) values(1, '[Amortizacion Hipoteca]', 3);
insert into categories (id, description, categoriesTypesid) values(2, '[Aygo]', 3);
insert into categories (id, description, categoriesTypesid) values(3, '[Bancos Anteriores]', 3);
insert into categories (id, description, categoriesTypesid) values(4, '[Berlingo]', 3);
insert into categories (id, description, categoriesTypesid) values(5, '[Binance]', 3);
insert into categories (id, description, categoriesTypesid) values(6, '[Bitdefender]', 3);
insert into categories (id, description, categoriesTypesid) values(7, '[Cartera ING]', 3);
insert into categories (id, description, categoriesTypesid) values(8, '[Cloud Microsoft]', 3);
insert into categories (id, description, categoriesTypesid) values(9, '[Coinbase]', 3);
insert into categories (id, description, categoriesTypesid) values(10, '[Corsa]', 3);
insert into categories (id, description, categoriesTypesid) values(11, '[Cumpleaños Ale]', 3);
insert into categories (id, description, categoriesTypesid) values(12, '[Cumpleaños Cris]', 3);
insert into categories (id, description, categoriesTypesid) values(13, '[Cumpleaños Richy]', 3);
insert into categories (id, description, categoriesTypesid) values(14, '[Daystar]', 3);
insert into categories (id, description, categoriesTypesid) values(15, '[Disney]', 3);
insert into categories (id, description, categoriesTypesid) values(16, '[Ducato]', 3);
insert into categories (id, description, categoriesTypesid) values(17, '[Edif. El Alfar]', 3);
insert into categories (id, description, categoriesTypesid) values(18, '[Efectivo]', 3);
insert into categories (id, description, categoriesTypesid) values(19, '[Faltante Mes]', 3);
insert into categories (id, description, categoriesTypesid) values(20, '[GDAX]', 3);
insert into categories (id, description, categoriesTypesid) values(21, '[Gimnasio Anual]', 3);
insert into categories (id, description, categoriesTypesid) values(22, '[Goin]', 3);
insert into categories (id, description, categoriesTypesid) values(23, '[Hipoteca Casa]', 3);
insert into categories (id, description, categoriesTypesid) values(24, '[Hipoteca Empresa]', 3);
insert into categories (id, description, categoriesTypesid) values(25, '[IBI y Basura]', 3);
insert into categories (id, description, categoriesTypesid) values(26, '[Ikea Family]', 3);
insert into categories (id, description, categoriesTypesid) values(27, '[ING 0723 Pagos]', 3);
insert into categories (id, description, categoriesTypesid) values(28, '[ING 2351 Principal]', 3);
insert into categories (id, description, categoriesTypesid) values(29, '[ING 4448 (Ahorros)]', 3);
insert into categories (id, description, categoriesTypesid) values(30, '[ITV Coches]', 3);
insert into categories (id, description, categoriesTypesid) values(31, '[Kona]', 3);
insert into categories (id, description, categoriesTypesid) values(32, '[Kymco]', 3);
insert into categories (id, description, categoriesTypesid) values(33, '[Matricula Colegio]', 3);
insert into categories (id, description, categoriesTypesid) values(34, '[Matricula Universidad]', 3);
insert into categories (id, description, categoriesTypesid) values(35, '[Medico Ale]', 3);
insert into categories (id, description, categoriesTypesid) values(36, '[NineyNine]', 3);
insert into categories (id, description, categoriesTypesid) values(37, '[PayPal]', 3);
insert into categories (id, description, categoriesTypesid) values(38, '[Ptmo (Berlingo)]', 3);
insert into categories (id, description, categoriesTypesid) values(39, '[Ptmo 6849 (Aygo)]', 3);
insert into categories (id, description, categoriesTypesid) values(40, '[Ptmo Ayuda Ana]', 3);
insert into categories (id, description, categoriesTypesid) values(41, '[Ptmo Caixa 1867 (Ducato)]', 3);
insert into categories (id, description, categoriesTypesid) values(42, '[Ptmo Caixa 7187 (Daelim)]', 3);
insert into categories (id, description, categoriesTypesid) values(43, '[Ptmo ING (Kona)]', 3);
insert into categories (id, description, categoriesTypesid) values(44, '[Ptmo ING 0022 (Ana)]', 3);
insert into categories (id, description, categoriesTypesid) values(45, '[Ptmo ING 0866 (Muebles)]', 3);
insert into categories (id, description, categoriesTypesid) values(46, '[Ptmo ING 31711]', 3);
insert into categories (id, description, categoriesTypesid) values(47, '[Ptmo ING 5179 (Ana3)]', 3);
insert into categories (id, description, categoriesTypesid) values(48, '[Ptmo ING 5466 (Ana2)]', 3);
insert into categories (id, description, categoriesTypesid) values(49, '[Ptmo ING 7185 (Cocina)]', 3);
insert into categories (id, description, categoriesTypesid) values(50, '[Ptmo Ing 9618 (Cocina2)]', 3);
insert into categories (id, description, categoriesTypesid) values(51, '[Ptmo Santander 0917(Sillon)]', 3);
insert into categories (id, description, categoriesTypesid) values(52, '[Ptmo Santander 0924(Corsa)]', 3);
insert into categories (id, description, categoriesTypesid) values(53, '[Quicken]', 3);
insert into categories (id, description, categoriesTypesid) values(54, '[Renta4 9155]', 3);
insert into categories (id, description, categoriesTypesid) values(55, '[Reparaciones Casa]', 3);
insert into categories (id, description, categoriesTypesid) values(56, '[Reparaciones Coche]', 3);
insert into categories (id, description, categoriesTypesid) values(57, '[Reyes]', 3);
insert into categories (id, description, categoriesTypesid) values(58, '[Rodaje Aygo]', 3);
insert into categories (id, description, categoriesTypesid) values(59, '[Rodaje Corsa]', 3);
insert into categories (id, description, categoriesTypesid) values(60, '[Rodaje Kona]', 3);
insert into categories (id, description, categoriesTypesid) values(61, '[Seguro Aygo]', 3);
insert into categories (id, description, categoriesTypesid) values(62, '[Seguro Corsa]', 3);
insert into categories (id, description, categoriesTypesid) values(63, '[Seguro Hogar]', 3);
insert into categories (id, description, categoriesTypesid) values(64, '[Seguro Kona]', 3);
insert into categories (id, description, categoriesTypesid) values(65, '[Sillon]', 3);
insert into categories (id, description, categoriesTypesid) values(66, '[Tarj. Twip]', 3);
insert into categories (id, description, categoriesTypesid) values(67, '[Tarj. Ventajon]', 3);
insert into categories (id, description, categoriesTypesid) values(68, '[Uphold]', 3);
insert into categories (id, description, categoriesTypesid) values(69, '[Venta Aygo Tino]', 3);
insert into categories (id, description, categoriesTypesid) values(70, '[Viajes]', 3);


insert into accounts (id,description,categoryid) values (1,'Amortizacion Hipoteca',1);
insert into accounts (id,description,categoryid) values (2,'Aygo',2);
insert into accounts (id,description,categoryid) values (3,'Bancos Anteriores',3);
insert into accounts (id,description,categoryid) values (4,'Berlingo',4);
insert into accounts (id,description,categoryid) values (5,'Binance',5);
insert into accounts (id,description,categoryid) values (6,'Bitdefender',6);
insert into accounts (id,description,categoryid) values (7,'Cartera ING',7);
insert into accounts (id,description,categoryid) values (8,'Cloud Microsoft',8);
insert into accounts (id,description,categoryid) values (9,'Coinbase',9);
insert into accounts (id,description,categoryid) values (10,'Corsa',10);
insert into accounts (id,description,categoryid) values (11,'Cumpleaños Ale',11);
insert into accounts (id,description,categoryid) values (12,'Cumpleaños Cris',12);
insert into accounts (id,description,categoryid) values (13,'Cumpleaños Richy',13);
insert into accounts (id,description,categoryid) values (14,'Daystar',14);
insert into accounts (id,description,categoryid) values (15,'Disney',15);
insert into accounts (id,description,categoryid) values (16,'Ducato',16);
insert into accounts (id,description,categoryid) values (17,'Edif. El Alfar',17);
insert into accounts (id,description,categoryid) values (18,'Efectivo',18);
insert into accounts (id,description,categoryid) values (19,'Faltante Mes',19);
insert into accounts (id,description,categoryid) values (20,'GDAX',20);
insert into accounts (id,description,categoryid) values (21,'Gimnasio Anual',21);
insert into accounts (id,description,categoryid) values (22,'Goin',22);
insert into accounts (id,description,categoryid) values (23,'Hipoteca Casa',23);
insert into accounts (id,description,categoryid) values (24,'Hipoteca Empresa',24);
insert into accounts (id,description,categoryid) values (25,'IBI y Basura',25);
insert into accounts (id,description,categoryid) values (26,'Ikea Family',26);
insert into accounts (id,description,categoryid) values (27,'ING 0723 Pagos',27);
insert into accounts (id,description,categoryid) values (28,'ING 2351 Principal',28);
insert into accounts (id,description,categoryid) values (29,'ING 4448 (Ahorros)',29);
insert into accounts (id,description,categoryid) values (30,'ITV Coches',30);
insert into accounts (id,description,categoryid) values (31,'Kona',31);
insert into accounts (id,description,categoryid) values (32,'Kymco',32);
insert into accounts (id,description,categoryid) values (33,'Matricula Colegio',33);
insert into accounts (id,description,categoryid) values (34,'Matricula Universidad',34);
insert into accounts (id,description,categoryid) values (35,'Medico Ale',35);
insert into accounts (id,description,categoryid) values (36,'NineyNine',36);
insert into accounts (id,description,categoryid) values (37,'PayPal',37);
insert into accounts (id,description,categoryid) values (38,'Ptmo (Berlingo)',38);
insert into accounts (id,description,categoryid) values (39,'Ptmo 6849 (Aygo)',39);
insert into accounts (id,description,categoryid) values (40,'Ptmo Ayuda Ana',40);
insert into accounts (id,description,categoryid) values (41,'Ptmo Caixa 1867 (Ducato)',41);
insert into accounts (id,description,categoryid) values (42,'Ptmo Caixa 7187 (Daelim)',42);
insert into accounts (id,description,categoryid) values (43,'Ptmo ING (Kona)',43);
insert into accounts (id,description,categoryid) values (44,'Ptmo ING 0022 (Ana)',44);
insert into accounts (id,description,categoryid) values (45,'Ptmo ING 0866 (Muebles)',45);
insert into accounts (id,description,categoryid) values (46,'Ptmo ING 31711',46);
insert into accounts (id,description,categoryid) values (47,'Ptmo ING 5179 (Ana3)',47);
insert into accounts (id,description,categoryid) values (48,'Ptmo ING 5466 (Ana2)',48);
insert into accounts (id,description,categoryid) values (49,'Ptmo ING 7185 (Cocina)',49);
insert into accounts (id,description,categoryid) values (50,'Ptmo Ing 9618 (Cocina2)',50);
insert into accounts (id,description,categoryid) values (51,'Ptmo Santander 0917(Sillon)',51);
insert into accounts (id,description,categoryid) values (52,'Ptmo Santander 0924(Corsa)',52);
insert into accounts (id,description,categoryid) values (53,'Quicken',53);
insert into accounts (id,description,categoryid) values (54,'Renta4 9155',54);
insert into accounts (id,description,categoryid) values (55,'Reparaciones Casa',55);
insert into accounts (id,description,categoryid) values (56,'Reparaciones Coche',56);
insert into accounts (id,description,categoryid) values (57,'Reyes',57);
insert into accounts (id,description,categoryid) values (58,'Rodaje Aygo',58);
insert into accounts (id,description,categoryid) values (59,'Rodaje Corsa',59);
insert into accounts (id,description,categoryid) values (60,'Rodaje Kona',60);
insert into accounts (id,description,categoryid) values (61,'Seguro Aygo',61);
insert into accounts (id,description,categoryid) values (62,'Seguro Corsa',62);
insert into accounts (id,description,categoryid) values (63,'Seguro Hogar',63);
insert into accounts (id,description,categoryid) values (64,'Seguro Kona',64);
insert into accounts (id,description,categoryid) values (65,'Sillon',65);
insert into accounts (id,description,categoryid) values (66,'Tarj. Twip',66);
insert into accounts (id,description,categoryid) values (67,'Tarj. Ventajon',67);
insert into accounts (id,description,categoryid) values (68,'Uphold',68);
insert into accounts (id,description,categoryid) values (69,'Venta Aygo Tino',69);
insert into accounts (id,description,categoryid) values (70,'Viajes',70);

