// <auto-generated />
using System;
using GARCA.DAO.Managers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GARCA.DAO.Migrations
{
    [DbContext(typeof(RYCContext))]
    [Migration("20230503002728_AutoregisterReminders")]
    partial class AutoregisterReminders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("GARCA.DAO.Models.Accounts", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("accountsTypesid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("closed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("accountsTypesid");

                    b.HasIndex("categoryid")
                        .IsUnique();

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("GARCA.DAO.Models.AccountsTypes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("accountsTypes");
                });

            modelBuilder.Entity("GARCA.DAO.Models.Categories", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("categoriesTypesid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("categoriesTypesid");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("GARCA.DAO.Models.CategoriesTypes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("categoriesTypes");
                });

            modelBuilder.Entity("GARCA.DAO.Models.DateCalendar", b =>
                {
                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("day")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("month")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("date");

                    b.ToTable("dateCalendar");
                });

            modelBuilder.Entity("GARCA.DAO.Models.ExpirationsReminders", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("date")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("done")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("transactionsRemindersid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("transactionsRemindersid");

                    b.ToTable("expirationsReminders");
                });

            modelBuilder.Entity("GARCA.DAO.Models.PeriodsReminders", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("periodsReminders");
                });

            modelBuilder.Entity("GARCA.DAO.Models.Persons", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("categoryid");

                    b.ToTable("persons");
                });

            modelBuilder.Entity("GARCA.DAO.Models.Splits", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("amountIn")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("amountOut")
                        .HasColumnType("TEXT");

                    b.Property<int?>("categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("memo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("tagid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tranferid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("transactionid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("categoryid");

                    b.HasIndex("tagid");

                    b.HasIndex("transactionid");

                    b.ToTable("splits");
                });

            modelBuilder.Entity("GARCA.DAO.Models.SplitsReminders", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("amountIn")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("amountOut")
                        .HasColumnType("TEXT");

                    b.Property<int?>("categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("memo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("tagid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tranferid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("transactionid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("categoryid");

                    b.HasIndex("tagid");

                    b.HasIndex("transactionid");

                    b.ToTable("splitsReminders");
                });

            modelBuilder.Entity("GARCA.DAO.Models.Tags", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("GARCA.DAO.Models.Transactions", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("accountid")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("amountIn")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("amountOut")
                        .HasColumnType("TEXT");

                    b.Property<int?>("categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("memo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("personid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tagid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tranferSplitid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tranferid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("transactionStatusid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("accountid");

                    b.HasIndex("categoryid");

                    b.HasIndex("personid");

                    b.HasIndex("tagid");

                    b.HasIndex("transactionStatusid");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("GARCA.DAO.Models.TransactionsReminders", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("accountid")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("amountIn")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("amountOut")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("autoRegister")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("memo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("periodsRemindersid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("personid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tagid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tranferSplitid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tranferid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("transactionStatusid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("accountid");

                    b.HasIndex("categoryid");

                    b.HasIndex("periodsRemindersid");

                    b.HasIndex("personid");

                    b.HasIndex("tagid");

                    b.HasIndex("transactionStatusid");

                    b.ToTable("transactionsReminders");
                });

            modelBuilder.Entity("GARCA.DAO.Models.TransactionsStatus", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("transactionsStatus");
                });

            modelBuilder.Entity("GARCA.DAO.Models.VBalancebyCategory", b =>
                {
                    b.Property<int?>("year")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("month")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("amount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("categoriesTypesid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .HasColumnType("TEXT");

                    b.HasKey("year", "month", "categoryid");

                    b.ToTable((string)null);

                    b.ToView("VBalancebyCategory", (string)null);
                });

            modelBuilder.Entity("GARCA.DAO.Models.Accounts", b =>
                {
                    b.HasOne("GARCA.DAO.Models.AccountsTypes", "accountsTypes")
                        .WithMany("accounts")
                        .HasForeignKey("accountsTypesid");

                    b.HasOne("GARCA.DAO.Models.Categories", "category")
                        .WithOne("accounts")
                        .HasForeignKey("GARCA.DAO.Models.Accounts", "categoryid");

                    b.Navigation("accountsTypes");

                    b.Navigation("category");
                });

            modelBuilder.Entity("GARCA.DAO.Models.Categories", b =>
                {
                    b.HasOne("GARCA.DAO.Models.CategoriesTypes", "categoriesTypes")
                        .WithMany("categories")
                        .HasForeignKey("categoriesTypesid");

                    b.Navigation("categoriesTypes");
                });

            modelBuilder.Entity("GARCA.DAO.Models.ExpirationsReminders", b =>
                {
                    b.HasOne("GARCA.DAO.Models.TransactionsReminders", "transactionsReminders")
                        .WithMany()
                        .HasForeignKey("transactionsRemindersid");

                    b.Navigation("transactionsReminders");
                });

            modelBuilder.Entity("GARCA.DAO.Models.Persons", b =>
                {
                    b.HasOne("GARCA.DAO.Models.Categories", "category")
                        .WithMany()
                        .HasForeignKey("categoryid");

                    b.Navigation("category");
                });

            modelBuilder.Entity("GARCA.DAO.Models.Splits", b =>
                {
                    b.HasOne("GARCA.DAO.Models.Categories", "category")
                        .WithMany()
                        .HasForeignKey("categoryid");

                    b.HasOne("GARCA.DAO.Models.Tags", "tag")
                        .WithMany()
                        .HasForeignKey("tagid");

                    b.HasOne("GARCA.DAO.Models.Transactions", "transaction")
                        .WithMany("splits")
                        .HasForeignKey("transactionid");

                    b.Navigation("category");

                    b.Navigation("tag");

                    b.Navigation("transaction");
                });

            modelBuilder.Entity("GARCA.DAO.Models.SplitsReminders", b =>
                {
                    b.HasOne("GARCA.DAO.Models.Categories", "category")
                        .WithMany()
                        .HasForeignKey("categoryid");

                    b.HasOne("GARCA.DAO.Models.Tags", "tag")
                        .WithMany()
                        .HasForeignKey("tagid");

                    b.HasOne("GARCA.DAO.Models.TransactionsReminders", "transaction")
                        .WithMany("splits")
                        .HasForeignKey("transactionid");

                    b.Navigation("category");

                    b.Navigation("tag");

                    b.Navigation("transaction");
                });

            modelBuilder.Entity("GARCA.DAO.Models.Transactions", b =>
                {
                    b.HasOne("GARCA.DAO.Models.Accounts", "account")
                        .WithMany()
                        .HasForeignKey("accountid");

                    b.HasOne("GARCA.DAO.Models.Categories", "category")
                        .WithMany()
                        .HasForeignKey("categoryid");

                    b.HasOne("GARCA.DAO.Models.Persons", "person")
                        .WithMany()
                        .HasForeignKey("personid");

                    b.HasOne("GARCA.DAO.Models.Tags", "tag")
                        .WithMany()
                        .HasForeignKey("tagid");

                    b.HasOne("GARCA.DAO.Models.TransactionsStatus", "transactionStatus")
                        .WithMany()
                        .HasForeignKey("transactionStatusid");

                    b.Navigation("account");

                    b.Navigation("category");

                    b.Navigation("person");

                    b.Navigation("tag");

                    b.Navigation("transactionStatus");
                });

            modelBuilder.Entity("GARCA.DAO.Models.TransactionsReminders", b =>
                {
                    b.HasOne("GARCA.DAO.Models.Accounts", "account")
                        .WithMany()
                        .HasForeignKey("accountid");

                    b.HasOne("GARCA.DAO.Models.Categories", "category")
                        .WithMany()
                        .HasForeignKey("categoryid");

                    b.HasOne("GARCA.DAO.Models.PeriodsReminders", "periodsReminders")
                        .WithMany()
                        .HasForeignKey("periodsRemindersid");

                    b.HasOne("GARCA.DAO.Models.Persons", "person")
                        .WithMany()
                        .HasForeignKey("personid");

                    b.HasOne("GARCA.DAO.Models.Tags", "tag")
                        .WithMany()
                        .HasForeignKey("tagid");

                    b.HasOne("GARCA.DAO.Models.TransactionsStatus", "transactionStatus")
                        .WithMany()
                        .HasForeignKey("transactionStatusid");

                    b.Navigation("account");

                    b.Navigation("category");

                    b.Navigation("periodsReminders");

                    b.Navigation("person");

                    b.Navigation("tag");

                    b.Navigation("transactionStatus");
                });

            modelBuilder.Entity("GARCA.DAO.Models.AccountsTypes", b =>
                {
                    b.Navigation("accounts");
                });

            modelBuilder.Entity("GARCA.DAO.Models.Categories", b =>
                {
                    b.Navigation("accounts");
                });

            modelBuilder.Entity("GARCA.DAO.Models.CategoriesTypes", b =>
                {
                    b.Navigation("categories");
                });

            modelBuilder.Entity("GARCA.DAO.Models.Transactions", b =>
                {
                    b.Navigation("splits");
                });

            modelBuilder.Entity("GARCA.DAO.Models.TransactionsReminders", b =>
                {
                    b.Navigation("splits");
                });
#pragma warning restore 612, 618
        }
    }
}
