select t.transid,t.TRANSDATE,t.ACCOUNTID,a.ACCOUNTNAME ,t.notes,c.CATEGID,c.CATEGNAME,t.TRANSAMOUNT 
from CHECKINGACCOUNT_V1 t
	inner join CATEGORY_V1 c on c.CATEGID = t.CATEGID 
	inner join ACCOUNTLIST_V1 a on a.ACCOUNTID = t.ACCOUNTID
where t.TRANSCODE = 'Deposit'
UNION 
select t.transid,t.TRANSDATE,t.ACCOUNTID,a.ACCOUNTNAME ,t.notes,c.CATEGID,c.CATEGNAME,-t.TRANSAMOUNT 
from CHECKINGACCOUNT_V1 t
	inner join CATEGORY_V1 c on c.CATEGID = t.CATEGID 
	inner join ACCOUNTLIST_V1 a on a.ACCOUNTID = t.ACCOUNTID
where t.TRANSCODE = 'Withdrawal'
union
select t.transid,t.TRANSDATE,t.ACCOUNTID,a.ACCOUNTNAME ,t.notes,a2.ACCOUNTID,a2.ACCOUNTNAME,-t.TRANSAMOUNT 
from CHECKINGACCOUNT_V1 t
	inner join ACCOUNTLIST_V1 a2 on a2.ACCOUNTID = t.TOACCOUNTID
	inner join ACCOUNTLIST_V1 a on a.ACCOUNTID = t.ACCOUNTID
where t.TRANSCODE = 'Transfer'
