# Generated by Django 5.1.6 on 2025-04-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountkeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='default_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ruta por defecto para adjuntos'),
        ),
    ]
