# Generated by Django 5.1.6 on 2025-04-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_default_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Cerrada'),
        ),
    ]
