// <auto-generated />
using System;
using DAOLib.Manager;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAOLib.Migrations
{
    [DbContext(typeof(RYCContext))]
    [Migration("20230509213217_AddActiveInvestmentProduct")]
    partial class AddActiveInvestmentProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("DAOLib.Models.Accounts", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("accountsTypesid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("closed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("accountsTypesid");

                    b.HasIndex("categoryid")
                        .IsUnique();

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("DAOLib.Models.AccountsTypes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("accountsTypes");
                });

            modelBuilder.Entity("DAOLib.Models.Categories", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("categoriesTypesid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("categoriesTypesid");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("DAOLib.Models.CategoriesTypes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("categoriesTypes");
                });

            modelBuilder.Entity("DAOLib.Models.DateCalendar", b =>
                {
                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("day")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("month")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("date");

                    b.ToTable("dateCalendar");
                });

            modelBuilder.Entity("DAOLib.Models.ExpirationsReminders", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("date")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("done")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("transactionsRemindersid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("transactionsRemindersid");

                    b.ToTable("expirationsReminders");
                });

            modelBuilder.Entity("DAOLib.Models.InvestmentProducts", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<string>("symbol")
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("investmentProducts");
                });

            modelBuilder.Entity("DAOLib.Models.InvestmentProductsPrices", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("investmentProductsid")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("prices")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("investmentProductsid");

                    b.ToTable("investmentProductsPrices");
                });

            modelBuilder.Entity("DAOLib.Models.PeriodsReminders", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("periodsReminders");
                });

            modelBuilder.Entity("DAOLib.Models.Persons", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("categoryid");

                    b.ToTable("persons");
                });

            modelBuilder.Entity("DAOLib.Models.Splits", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("amountIn")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("amountOut")
                        .HasColumnType("TEXT");

                    b.Property<int?>("categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("memo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("tagid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tranferid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("transactionid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("categoryid");

                    b.HasIndex("tagid");

                    b.HasIndex("transactionid");

                    b.ToTable("splits");
                });

            modelBuilder.Entity("DAOLib.Models.SplitsReminders", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("amountIn")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("amountOut")
                        .HasColumnType("TEXT");

                    b.Property<int?>("categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("memo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("tagid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tranferid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("transactionid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("categoryid");

                    b.HasIndex("tagid");

                    b.HasIndex("transactionid");

                    b.ToTable("splitsReminders");
                });

            modelBuilder.Entity("DAOLib.Models.Tags", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("DAOLib.Models.Transactions", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("accountid")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("amountIn")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("amountOut")
                        .HasColumnType("TEXT");

                    b.Property<int?>("categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("date")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("investmentCategory")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("investmentProductsid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("memo")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("numShares")
                        .HasColumnType("TEXT");

                    b.Property<int?>("personid")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("pricesShares")
                        .HasColumnType("TEXT");

                    b.Property<int?>("tagid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tranferSplitid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tranferid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("transactionStatusid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("accountid");

                    b.HasIndex("categoryid");

                    b.HasIndex("investmentProductsid");

                    b.HasIndex("personid");

                    b.HasIndex("tagid");

                    b.HasIndex("transactionStatusid");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("DAOLib.Models.TransactionsReminders", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("accountid")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("amountIn")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("amountOut")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("autoRegister")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("memo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("periodsRemindersid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("personid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tagid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tranferSplitid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tranferid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("transactionStatusid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("accountid");

                    b.HasIndex("categoryid");

                    b.HasIndex("periodsRemindersid");

                    b.HasIndex("personid");

                    b.HasIndex("tagid");

                    b.HasIndex("transactionStatusid");

                    b.ToTable("transactionsReminders");
                });

            modelBuilder.Entity("DAOLib.Models.TransactionsStatus", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("transactionsStatus");
                });

            modelBuilder.Entity("DAOLib.Models.VBalancebyCategory", b =>
                {
                    b.Property<int?>("year")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("month")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("amount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("categoriesTypesid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .HasColumnType("TEXT");

                    b.HasKey("year", "month", "categoryid");

                    b.ToTable((string)null);

                    b.ToView("VBalancebyCategory", (string)null);
                });

            modelBuilder.Entity("DAOLib.Models.Accounts", b =>
                {
                    b.HasOne("DAOLib.Models.AccountsTypes", "accountsTypes")
                        .WithMany("accounts")
                        .HasForeignKey("accountsTypesid");

                    b.HasOne("DAOLib.Models.Categories", "category")
                        .WithOne("accounts")
                        .HasForeignKey("DAOLib.Models.Accounts", "categoryid");

                    b.Navigation("accountsTypes");

                    b.Navigation("category");
                });

            modelBuilder.Entity("DAOLib.Models.Categories", b =>
                {
                    b.HasOne("DAOLib.Models.CategoriesTypes", "categoriesTypes")
                        .WithMany("categories")
                        .HasForeignKey("categoriesTypesid");

                    b.Navigation("categoriesTypes");
                });

            modelBuilder.Entity("DAOLib.Models.ExpirationsReminders", b =>
                {
                    b.HasOne("DAOLib.Models.TransactionsReminders", "transactionsReminders")
                        .WithMany()
                        .HasForeignKey("transactionsRemindersid");

                    b.Navigation("transactionsReminders");
                });

            modelBuilder.Entity("DAOLib.Models.InvestmentProductsPrices", b =>
                {
                    b.HasOne("DAOLib.Models.InvestmentProducts", "investmentProducts")
                        .WithMany()
                        .HasForeignKey("investmentProductsid");

                    b.Navigation("investmentProducts");
                });

            modelBuilder.Entity("DAOLib.Models.Persons", b =>
                {
                    b.HasOne("DAOLib.Models.Categories", "category")
                        .WithMany()
                        .HasForeignKey("categoryid");

                    b.Navigation("category");
                });

            modelBuilder.Entity("DAOLib.Models.Splits", b =>
                {
                    b.HasOne("DAOLib.Models.Categories", "category")
                        .WithMany()
                        .HasForeignKey("categoryid");

                    b.HasOne("DAOLib.Models.Tags", "tag")
                        .WithMany()
                        .HasForeignKey("tagid");

                    b.HasOne("DAOLib.Models.Transactions", "transaction")
                        .WithMany("splits")
                        .HasForeignKey("transactionid");

                    b.Navigation("category");

                    b.Navigation("tag");

                    b.Navigation("transaction");
                });

            modelBuilder.Entity("DAOLib.Models.SplitsReminders", b =>
                {
                    b.HasOne("DAOLib.Models.Categories", "category")
                        .WithMany()
                        .HasForeignKey("categoryid");

                    b.HasOne("DAOLib.Models.Tags", "tag")
                        .WithMany()
                        .HasForeignKey("tagid");

                    b.HasOne("DAOLib.Models.TransactionsReminders", "transaction")
                        .WithMany("splits")
                        .HasForeignKey("transactionid");

                    b.Navigation("category");

                    b.Navigation("tag");

                    b.Navigation("transaction");
                });

            modelBuilder.Entity("DAOLib.Models.Transactions", b =>
                {
                    b.HasOne("DAOLib.Models.Accounts", "account")
                        .WithMany()
                        .HasForeignKey("accountid");

                    b.HasOne("DAOLib.Models.Categories", "category")
                        .WithMany()
                        .HasForeignKey("categoryid");

                    b.HasOne("DAOLib.Models.InvestmentProducts", "investmentProducts")
                        .WithMany()
                        .HasForeignKey("investmentProductsid");

                    b.HasOne("DAOLib.Models.Persons", "person")
                        .WithMany()
                        .HasForeignKey("personid");

                    b.HasOne("DAOLib.Models.Tags", "tag")
                        .WithMany()
                        .HasForeignKey("tagid");

                    b.HasOne("DAOLib.Models.TransactionsStatus", "transactionStatus")
                        .WithMany()
                        .HasForeignKey("transactionStatusid");

                    b.Navigation("account");

                    b.Navigation("category");

                    b.Navigation("investmentProducts");

                    b.Navigation("person");

                    b.Navigation("tag");

                    b.Navigation("transactionStatus");
                });

            modelBuilder.Entity("DAOLib.Models.TransactionsReminders", b =>
                {
                    b.HasOne("DAOLib.Models.Accounts", "account")
                        .WithMany()
                        .HasForeignKey("accountid");

                    b.HasOne("DAOLib.Models.Categories", "category")
                        .WithMany()
                        .HasForeignKey("categoryid");

                    b.HasOne("DAOLib.Models.PeriodsReminders", "periodsReminders")
                        .WithMany()
                        .HasForeignKey("periodsRemindersid");

                    b.HasOne("DAOLib.Models.Persons", "person")
                        .WithMany()
                        .HasForeignKey("personid");

                    b.HasOne("DAOLib.Models.Tags", "tag")
                        .WithMany()
                        .HasForeignKey("tagid");

                    b.HasOne("DAOLib.Models.TransactionsStatus", "transactionStatus")
                        .WithMany()
                        .HasForeignKey("transactionStatusid");

                    b.Navigation("account");

                    b.Navigation("category");

                    b.Navigation("periodsReminders");

                    b.Navigation("person");

                    b.Navigation("tag");

                    b.Navigation("transactionStatus");
                });

            modelBuilder.Entity("DAOLib.Models.AccountsTypes", b =>
                {
                    b.Navigation("accounts");
                });

            modelBuilder.Entity("DAOLib.Models.Categories", b =>
                {
                    b.Navigation("accounts");
                });

            modelBuilder.Entity("DAOLib.Models.CategoriesTypes", b =>
                {
                    b.Navigation("categories");
                });

            modelBuilder.Entity("DAOLib.Models.Transactions", b =>
                {
                    b.Navigation("splits");
                });

            modelBuilder.Entity("DAOLib.Models.TransactionsReminders", b =>
                {
                    b.Navigation("splits");
                });
#pragma warning restore 612, 618
        }
    }
}
