# Generated by Django 5.1.6 on 2025-04-04 15:14

import entries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_alter_entry_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='balance',
            field=models.JSONField(default=entries.models.get_default_balance),
        ),
    ]
