# Generated by Django 5.1.6 on 2025-04-15 20:40

import attachments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_alter_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=attachments.models.get_attachment_upload_path),
        ),
    ]
