# Generated by Django 5.1.6 on 2025-04-21 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='documentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Archivo de Factura')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Procesar'), ('PROCESSING', 'Procesando'), ('PROCESSED', 'Procesado'), ('FAILED', 'Error en Procesamiento'), ('NEEDS_MAPPING', 'Necesita Mapeo Manual')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='Texto Extraído (OCR)')),
            ],
            options={
                'verbose_name': 'Documento de Factura',
                'verbose_name_plural': 'Documentos de Factura',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='documentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tipo')),
                ('date_extraction_rule', models.CharField(blank=True, max_length=255, null=True, verbose_name='Regla Extracción Fecha')),
                ('total_extraction_rule', models.CharField(blank=True, max_length=255, null=True, verbose_name='Regla Extracción Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Factura (Plantilla)',
                'verbose_name_plural': 'Tipos de Factura (Plantillas)',
            },
        ),
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Fecha Factura')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Importe Total')),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_data', to='document_classified.documentdocument', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Dato Extraído',
                'verbose_name_plural': 'Datos Extraídos',
            },
        ),
        migrations.AddField(
            model_name='documentdocument',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='document_classified.documenttype', verbose_name='Tipo de Factura'),
        ),
    ]
