# Generated by Django 5.1.6 on 2025-04-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_classified', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='date_extraction_rule',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='total_extraction_rule',
        ),
        migrations.AddField(
            model_name='documenttype',
            name='extraction_rules',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Reglas de Extracción (JSON)'),
        ),
    ]
