# Generated by Django X.Y on YYYY-MM-DD HH:MM
from django.db import migrations

# Define las sentencias SQL
# Es buena práctica usar triple comilla para SQL multilínea
SQL_FORWARD = """
INSERT INTO document_classified_documenttype (name, created_at, updated_at, extraction_rules) VALUES
('Vizenter', '2025-04-21 15:09:31.002508', '2025-04-21 16:42:35.743958', '{"identifier": {"type": "keyword", "value": "78607155-D"}, "date": {"type": "regex", "pattern": "FECHA.*?(\\\\d{1,2}[./-]\\\\d{1,2}[./-]\\\\d{2,4})"}, "total": {"type": "regex", "pattern": "TOTAL:\\\\s*(\\\\d+,\\\\d+)"}}'),
('Endesa', '2025-04-21 15:40:07.954947', '2025-04-21 17:10:35.700836', '{"identifier": {"type": "keyword", "value": "A81948077"}, "date": {"type": "regex", "pattern": "Fecha de cargo:\\\\s*(\\\\d{1,2}\\\\s+de\\\\s+\\\\w+\\\\s+de\\\\s+\\\\d{4})"}, "total": {"type": "regex", "pattern": "Total\\\\s*(\\\\d+,\\\\d+)\\\\s*\u20ac?"}}');
"""

# (Opcional) Define el SQL para revertir la migración (eliminar los datos)
SQL_REVERSE = """
DELETE FROM document_classified_documenttype WHERE name IN ('Vizenter', 'Endesa');
"""

class Migration(migrations.Migration):

    # Añade la dependencia a la migración anterior de document_classified
    # Reemplaza '000Y_previous_migration' con el nombre real de la migración anterior
    dependencies = [
        ('document_classified', '0002_remove_documenttype_date_extraction_rule_and_more'),
    ]

    operations = [
        # Ejecuta el SQL para insertar los datos
        migrations.RunSQL(SQL_FORWARD, reverse_sql=SQL_REVERSE),
    ]

