# Generated by Django 5.1.6 on 2025-04-21 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_balance'),
        ('document_classified', '0003_seed_initial_document_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_types', to='accounts.account', verbose_name='Cuenta Contable Asociada'),
        ),
    ]
