# Generated by Django 5.1.6 on 2025-04-22 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_classified', '0005_seed_update_document_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='documentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('file', models.FileField(upload_to='documents', verbose_name='Archivo de Factura')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Procesar'), ('PROCESSING', 'Procesando'), ('PROCESSED', 'Procesado'), ('FAILED', 'Error en Procesamiento'), ('NEEDS_MAPPING', 'Necesita Mapeo Manual'), ('ASSOCIATED', 'Asociado a Transacción')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='Texto Extraído (OCR)')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='document_classified.documenttype', verbose_name='Tipo de Factura')),
            ],
            options={
                'verbose_name': 'Documento de Factura',
                'verbose_name_plural': 'Documentos de Factura',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_data', to='document_classified.documentinfo', verbose_name='Documento'),
        ),
        migrations.DeleteModel(
            name='documentDocument',
        ),
    ]
