// <auto-generated />
using System;
using GARCA.Data.Managers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GARCA.DAO.Migrations
{
    [DbContext(typeof(RycContext))]
    [Migration("20230608214525_addInvestmentProductsTypes")]
    partial class addInvestmentProductsTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("GARCA_MODEL.AccountsDAO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("accountsTypesid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("closed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("accountsTypesid");

                    b.HasIndex("categoryid");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("GARCA_MODEL.AccountsTypesDAO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("AccountsTypes");
                });

            modelBuilder.Entity("GARCA_MODEL.CategoriesDAO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("categoriesTypesid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("categoriesTypesid");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("GARCA_MODEL.CategoriesTypesDAO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("CategoriesTypes");
                });

            modelBuilder.Entity("GARCA_MODEL.DateCalendarDAO", b =>
                {
                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("day")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("month")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("date");

                    b.ToTable("DateCalendar");
                });

            modelBuilder.Entity("GARCA_MODEL.ExpirationsRemindersDAO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("date")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("done")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("transactionsRemindersid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("transactionsRemindersid");

                    b.ToTable("ExpirationsReminders");
                });

            modelBuilder.Entity("GARCA_MODEL.InvestmentProductsDAO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("investmentProductsTypesid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("symbol")
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("investmentProductsTypesid");

                    b.ToTable("InvestmentProducts");
                });

            modelBuilder.Entity("GARCA_MODEL.InvestmentProductsPricesDAO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("investmentProductsid")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("prices")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("investmentProductsid");

                    b.ToTable("InvestmentProductsPrices");
                });

            modelBuilder.Entity("GARCA_MODEL.InvestmentProductsTypesDAO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("InvestmentProductsTypes");
                });

            modelBuilder.Entity("GARCA_MODEL.PeriodsRemindersDAO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("PeriodsReminders");
                });

            modelBuilder.Entity("GARCA_MODEL.PersonsDAO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("categoryid");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("GARCA_MODEL.SplitsDAO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("amountIn")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("amountOut")
                        .HasColumnType("TEXT");

                    b.Property<int?>("categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("memo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("tagid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tranferid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("transactionid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("categoryid");

                    b.HasIndex("tagid");

                    b.HasIndex("transactionid");

                    b.ToTable("Splits");
                });

            modelBuilder.Entity("GARCA_MODEL.SplitsReminders", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("amountIn")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("amountOut")
                        .HasColumnType("TEXT");

                    b.Property<int?>("categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("memo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("tagid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tranferid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("transactionid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("categoryid");

                    b.HasIndex("tagid");

                    b.HasIndex("transactionid");

                    b.ToTable("SplitsReminders");
                });

            modelBuilder.Entity("GARCA_MODEL.TagsDAO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("GARCA_MODEL.TransactionsDAO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("accountid")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("amountIn")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("amountOut")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("balance")
                        .HasColumnType("TEXT");

                    b.Property<int?>("categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("date")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("investmentCategory")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("investmentProductsid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("memo")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("numShares")
                        .HasColumnType("TEXT");

                    b.Property<int?>("personid")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("pricesShares")
                        .HasColumnType("TEXT");

                    b.Property<int?>("tagid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tranferSplitid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tranferid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("transactionStatusid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("accountid");

                    b.HasIndex("categoryid");

                    b.HasIndex("investmentProductsid");

                    b.HasIndex("personid");

                    b.HasIndex("tagid");

                    b.HasIndex("transactionStatusid");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("GARCA_MODEL.TransactionsRemindersDAO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("accountid")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("amountIn")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("amountOut")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("autoRegister")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("memo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("periodsRemindersid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("personid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tagid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("transactionStatusid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("accountid");

                    b.HasIndex("categoryid");

                    b.HasIndex("periodsRemindersid");

                    b.HasIndex("personid");

                    b.HasIndex("tagid");

                    b.HasIndex("transactionStatusid");

                    b.ToTable("TransactionsReminders");
                });

            modelBuilder.Entity("GARCA_MODEL.TransactionsStatusDAO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("TransactionsStatus");
                });

            modelBuilder.Entity("GARCA_MODEL.VBalancebyCategoryDAO", b =>
                {
                    b.Property<int?>("year")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("month")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("amount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("categoriesTypesid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .HasColumnType("TEXT");

                    b.HasKey("year", "month", "categoryid");

                    b.ToTable("VBalancebyCategory");

                    b.ToView("VBalancebyCategory", (string)null);
                });

            modelBuilder.Entity("GARCA_MODEL.AccountsDAO", b =>
                {
                    b.HasOne("GARCA_MODEL.AccountsTypesDAO", "accountsTypes")
                        .WithMany()
                        .HasForeignKey("accountsTypesid");

                    b.HasOne("GARCA_MODEL.CategoriesDAO", "category")
                        .WithMany()
                        .HasForeignKey("categoryid");

                    b.Navigation("accountsTypes");

                    b.Navigation("category");
                });

            modelBuilder.Entity("GARCA_MODEL.CategoriesDAO", b =>
                {
                    b.HasOne("GARCA_MODEL.CategoriesTypesDAO", "categoriesTypes")
                        .WithMany()
                        .HasForeignKey("categoriesTypesid");

                    b.Navigation("categoriesTypes");
                });

            modelBuilder.Entity("GARCA_MODEL.ExpirationsRemindersDAO", b =>
                {
                    b.HasOne("GARCA_MODEL.TransactionsRemindersDAO", "transactionsReminders")
                        .WithMany()
                        .HasForeignKey("transactionsRemindersid");

                    b.Navigation("transactionsReminders");
                });

            modelBuilder.Entity("GARCA_MODEL.InvestmentProductsDAO", b =>
                {
                    b.HasOne("GARCA_MODEL.InvestmentProductsTypesDAO", "investmentProductsTypes")
                        .WithMany()
                        .HasForeignKey("investmentProductsTypesid");

                    b.Navigation("investmentProductsTypes");
                });

            modelBuilder.Entity("GARCA_MODEL.InvestmentProductsPricesDAO", b =>
                {
                    b.HasOne("GARCA_MODEL.InvestmentProductsDAO", "investmentProducts")
                        .WithMany()
                        .HasForeignKey("investmentProductsid");

                    b.Navigation("investmentProducts");
                });

            modelBuilder.Entity("GARCA_MODEL.PersonsDAO", b =>
                {
                    b.HasOne("GARCA_MODEL.CategoriesDAO", "category")
                        .WithMany()
                        .HasForeignKey("categoryid");

                    b.Navigation("category");
                });

            modelBuilder.Entity("GARCA_MODEL.SplitsDAO", b =>
                {
                    b.HasOne("GARCA_MODEL.CategoriesDAO", "category")
                        .WithMany()
                        .HasForeignKey("categoryid");

                    b.HasOne("GARCA_MODEL.TagsDAO", "tag")
                        .WithMany()
                        .HasForeignKey("tagid");

                    b.HasOne("GARCA_MODEL.TransactionsDAO", "transaction")
                        .WithMany("splits")
                        .HasForeignKey("transactionid");

                    b.Navigation("category");

                    b.Navigation("tag");

                    b.Navigation("transaction");
                });

            modelBuilder.Entity("GARCA_MODEL.SplitsReminders", b =>
                {
                    b.HasOne("GARCA_MODEL.CategoriesDAO", "category")
                        .WithMany()
                        .HasForeignKey("categoryid");

                    b.HasOne("GARCA_MODEL.TagsDAO", "tag")
                        .WithMany()
                        .HasForeignKey("tagid");

                    b.HasOne("GARCA_MODEL.TransactionsRemindersDAO", "transaction")
                        .WithMany("splits")
                        .HasForeignKey("transactionid");

                    b.Navigation("category");

                    b.Navigation("tag");

                    b.Navigation("transaction");
                });

            modelBuilder.Entity("GARCA_MODEL.TransactionsDAO", b =>
                {
                    b.HasOne("GARCA_MODEL.AccountsDAO", "account")
                        .WithMany()
                        .HasForeignKey("accountid");

                    b.HasOne("GARCA_MODEL.CategoriesDAO", "category")
                        .WithMany()
                        .HasForeignKey("categoryid");

                    b.HasOne("GARCA_MODEL.InvestmentProductsDAO", "investmentProducts")
                        .WithMany()
                        .HasForeignKey("investmentProductsid");

                    b.HasOne("GARCA_MODEL.PersonsDAO", "person")
                        .WithMany()
                        .HasForeignKey("personid");

                    b.HasOne("GARCA_MODEL.TagsDAO", "tag")
                        .WithMany()
                        .HasForeignKey("tagid");

                    b.HasOne("GARCA_MODEL.TransactionsStatusDAO", "transactionStatus")
                        .WithMany()
                        .HasForeignKey("transactionStatusid");

                    b.Navigation("account");

                    b.Navigation("category");

                    b.Navigation("investmentProducts");

                    b.Navigation("person");

                    b.Navigation("tag");

                    b.Navigation("transactionStatus");
                });

            modelBuilder.Entity("GARCA_MODEL.TransactionsRemindersDAO", b =>
                {
                    b.HasOne("GARCA_MODEL.AccountsDAO", "account")
                        .WithMany()
                        .HasForeignKey("accountid");

                    b.HasOne("GARCA_MODEL.CategoriesDAO", "category")
                        .WithMany()
                        .HasForeignKey("categoryid");

                    b.HasOne("GARCA_MODEL.PeriodsRemindersDAO", "periodsReminders")
                        .WithMany()
                        .HasForeignKey("periodsRemindersid");

                    b.HasOne("GARCA_MODEL.PersonsDAO", "person")
                        .WithMany()
                        .HasForeignKey("personid");

                    b.HasOne("GARCA_MODEL.TagsDAO", "tag")
                        .WithMany()
                        .HasForeignKey("tagid");

                    b.HasOne("GARCA_MODEL.TransactionsStatusDAO", "transactionStatus")
                        .WithMany()
                        .HasForeignKey("transactionStatusid");

                    b.Navigation("account");

                    b.Navigation("category");

                    b.Navigation("periodsReminders");

                    b.Navigation("person");

                    b.Navigation("tag");

                    b.Navigation("transactionStatus");
                });

            modelBuilder.Entity("GARCA_MODEL.TransactionsDAO", b =>
                {
                    b.Navigation("splits");
                });

            modelBuilder.Entity("GARCA_MODEL.TransactionsRemindersDAO", b =>
                {
                    b.Navigation("splits");
                });
#pragma warning restore 612, 618
        }
    }
}
